/**
 * Danh mục 20 Thủ tục Lãnh sự Việt Nam tại Nhật Bản (MVP)
 * Căn cứ theo quy định của Luật Cơ quan đại diện ngoại giao, Luật Hộ tịch, Luật Xuất nhập cảnh,
 * và các thông báo, hướng dẫn chính thức từ Đại sứ quán VN tại Tokyo, Tổng Lãnh sự quán VN tại Osaka & Fukuoka.
 */

export const CONSULAR_CATEGORIES = [
  {
    id: 'passport',
    name: {
      vi: 'Hộ chiếu & Giấy tờ đi lại',
      en: 'Passport & Travel Documents',
      ja: 'パスポート・渡航文書',
    },
    icon: 'BookOpen',
    color: 'sky',
  },
  {
    id: 'birth_nationality',
    name: {
      vi: 'Khai sinh & Quốc tịch',
      en: 'Birth Registration & Nationality',
      ja: '出生届出・国籍',
    },
    icon: 'Baby',
    color: 'emerald',
  },
  {
    id: 'marriage_family',
    name: {
      vi: 'Hôn nhân & Gia đình',
      en: 'Marriage & Family Affairs',
      ja: '婚姻・家族',
    },
    icon: 'HeartHandshake',
    color: 'rose',
  },
  {
    id: 'legalization_auth',
    name: {
      vi: 'Hợp pháp hóa & Chứng thực',
      en: 'Legalization & Certification',
      ja: '領事認証・公証',
    },
    icon: 'Stamp',
    color: 'amber',
  },
  {
    id: 'death_civil',
    name: {
      vi: 'Khai tử & Hộ tịch khác',
      en: 'Death Registration & Civil Status',
      ja: '死亡届出・身分証明',
    },
    icon: 'FileText',
    color: 'slate',
  },
  {
    id: 'protection_emergency',
    name: {
      vi: 'Bảo hộ công dân & Khẩn cấp',
      en: 'Citizen Protection & Emergency',
      ja: '邦人保護・緊急支援',
    },
    icon: 'ShieldAlert',
    color: 'red',
  },
  {
    id: 'visa_other',
    name: {
      vi: 'Miễn thị thực & Thủ tục khác',
      en: 'Visa Exemption & Other Affairs',
      ja: '査証免除・その他',
    },
    icon: 'Layers',
    color: 'indigo',
  },
];

export const CONSULAR_PROCEDURES = [
  // 1. Nhóm Hộ chiếu & Giấy đi lại
  {
    id: 'vn_passport_renewal',
    category: 'passport',
    title: {
      vi: 'Cấp lại hộ chiếu hết hạn hoặc sắp hết hạn',
      en: 'Passport Renewal (Expiring or Expired)',
      ja: '一般旅券の更新・再発給（期限切れ・残存期間不足）',
    },
    summary: 'Áp dụng cho công dân Việt Nam đang có tư cách lưu trú hợp pháp tại Nhật Bản có hộ chiếu còn hạn dưới 6 tháng hoặc đã hết hạn.',
    when_needed: 'Khi hộ chiếu hiện tại còn hạn dưới 6 tháng hoặc đã hết hạn, cần làm hộ chiếu mới để gia hạn tư cách lưu trú (Visa) hoặc xuất nhập cảnh.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 10 ngày làm việc (kể từ khi nhận đủ hồ sơ hợp lệ)',
    fee_note: 'Theo biểu mức lệ phí lãnh sự hiện hành quy định tại Thông tư 264/2016/TT-BTC',
    formId: 'form_passport_tk02',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['đổi hộ chiếu', 'hết hạn passport', 'gia hạn hộ chiếu', 'làm lại hộ chiếu nhật', 'sắp hết hạn visa', 'hộ chiếu hết trang'],
    related_jp_procedures: ['status-change-guide-jp'],
    required_documents: [
      {
        name: 'Tờ khai đề nghị cấp hộ chiếu (Mẫu TK02)',
        quantity: '01 bản gốc',
        originalOrCopy: 'Gốc',
        note: 'Điền và in từ Toolio, ký tên rõ ràng',
        isForm: true,
        formId: 'form_passport_tk02',
      },
      {
        name: 'Ảnh thẻ chuẩn quốc tế (4x6 cm)',
        quantity: '02 ảnh',
        originalOrCopy: 'Gốc',
        note: 'Nền trắng, áo màu sẫm có cổ, chụp không quá 6 tháng, không đeo kính râm, ghi họ tên ngày sinh mặt sau',
      },
      {
        name: 'Hộ chiếu gốc hiện tại',
        quantity: '01 bản',
        originalOrCopy: 'Gốc',
        note: 'Gửi kèm hộ chiếu gốc để cơ quan đại diện hủy giá trị sử dụng và trả lại sau khi có hộ chiếu mới',
      },
      {
        name: 'Thẻ ngoại kiều (Zairyu Card) 2 mặt',
        quantity: '01 bản photo',
        originalOrCopy: 'Photo',
        note: 'Sao y rõ nét hai mặt thẻ còn hạn lưu trú tại Nhật',
      },
      {
        name: 'Bì thư gửi trả kết quả (Letter Pack Plus 600 màu đỏ)',
        quantity: '01 bì thư',
        originalOrCopy: 'Gốc',
        note: 'Ghi sẵn họ tên, địa chỉ, số điện thoại người nhận tại Nhật Bản, giữ lại mã Tracking',
      },
    ],
    steps: [
      {
        step: 1,
        title: 'Điền Tờ khai TK02 trực tuyến',
        desc: 'Sử dụng công cụ Easy Fill trên Toolio để điền chính xác thông tin nhân thân và xuất bản in A4 chuẩn theo Thông tư 31/2023/TT-BCA.',
      },
      {
        step: 2,
        title: 'Chuẩn bị hồ sơ & Bì thư Letter Pack đỏ',
        desc: 'Chụp 02 ảnh 4x6 cm đúng chuẩn, photo thẻ Zairyu Card, mua phong bì Letter Pack Plus (đỏ) tại bưu điện hoặc combini.',
      },
      {
        step: 3,
        title: 'Gửi hồ sơ qua bưu điện hoặc nộp trực tiếp',
        desc: 'Gửi đảm bảo (Kan-i Kakitome hoặc Letter Pack đỏ) đến cơ quan đại diện có thẩm quyền tại khu vực của bạn (Tokyo, Osaka, hoặc Fukuoka).',
      },
      {
        step: 4,
        title: 'Nhận hộ chiếu mới qua bưu điện',
        desc: 'Sau 5-10 ngày làm việc, bưu tá JP Post sẽ giao tận tay hộ chiếu mới và hộ chiếu cũ đã bấm lỗ hủy.',
      },
    ],
    official_sources: [
      {
        title: 'Đại sứ quán Việt Nam tại Nhật Bản - Cấp lại hộ chiếu hết hạn',
        url: 'https://vnembassy-jp.org/vi/cap-ho-chieu-pho-thong-cho-nguoi-da-tung-co-ho-chieu-viet-nam',
      },
      {
        title: 'Tổng Lãnh sự quán Việt Nam tại Osaka - Hướng dẫn cấp hộ chiếu',
        url: 'https://vnconsulate-osaka.org/vi/thu-tuc-ho-chieu',
      },
    ],
  },
  {
    id: 'vn_passport_lost',
    category: 'passport',
    title: {
      vi: 'Cấp lại hộ chiếu do bị mất tại Nhật Bản',
      en: 'Replacement of Lost Passport',
      ja: '紛失による一般旅券の再発給',
    },
    summary: 'Áp dụng cho công dân Việt Nam bị đánh mất hoặc thất lạc hộ chiếu tại Nhật Bản.',
    when_needed: 'Khi bị mất hộ chiếu trong quá trình sinh sống, học tập hoặc công tác tại Nhật.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 7 - 15 ngày làm việc (cần xác minh nhân thân với cơ quan trong nước)',
    formId: 'form_passport_tk02',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['mất hộ chiếu', 'mất passport', 'thất lạc hộ chiếu', 'báo mất hộ chiếu'],
    related_jp_procedures: ['certificate-acquisition-guide-jp'],
    required_documents: [
      {
        name: 'Tờ khai đề nghị cấp hộ chiếu (Mẫu TK02)',
        quantity: '01 bản gốc',
        originalOrCopy: 'Gốc',
        note: 'Chọn lý do cấp lại do bị mất',
        isForm: true,
        formId: 'form_passport_tk02',
      },
      {
        name: 'Đơn báo mất hộ chiếu (Đơn cớ mất)',
        quantity: '01 bản gốc',
        originalOrCopy: 'Gốc',
        note: 'Có xác nhận của Cảnh sát Nhật Bản (Ibutsu Todokede Shomeisho - 遺失届出証明書)',
      },
      {
        name: 'Giấy chứng nhận đăng ký báo mất của cảnh sát Nhật (Ibutsu Shomeisho)',
        quantity: '01 bản gốc',
        originalOrCopy: 'Gốc',
        note: 'Xin tại Đồn Cảnh sát (Koban / Keisatsusho) nơi báo mất',
      },
      {
        name: 'Ảnh thẻ chuẩn quốc tế (4x6 cm)',
        quantity: '02 ảnh',
        originalOrCopy: 'Gốc',
        note: 'Nền trắng, mới chụp trong vòng 6 tháng',
      },
      {
        name: 'Bản photo hộ chiếu cũ (nếu còn giữ) hoặc CCCD',
        quantity: '01 bản',
        originalOrCopy: 'Photo',
        note: 'Giúp đẩy nhanh quá trình tra cứu dữ liệu xuất nhập cảnh',
      },
      {
        name: 'Thẻ ngoại kiều (Zairyu Card)',
        quantity: '01 bản photo',
        originalOrCopy: 'Photo',
        note: 'Bản sao rõ nét 2 mặt',
      },
      {
        name: 'Bì thư gửi trả kết quả (Letter Pack đỏ)',
        quantity: '01 bì thư',
        originalOrCopy: 'Gốc',
        note: 'Ghi sẵn địa chỉ nhận',
      },
    ],
    steps: [
      {
        step: 1,
        title: 'Báo cảnh sát Nhật Bản (Koban/Keisatsusho) ngay lập tức',
        desc: 'Đến đồn cảnh sát gần nhất khai báo mất tài sản và xin Giấy chứng nhận đã trình báo mất (Ibutsu Todoke / 遺失届番号).',
      },
      {
        step: 2,
        title: 'Điền Tờ khai TK02 và Đơn báo mất',
        desc: 'Điền form TK02 trên Toolio, nêu rõ ngày giờ mất và số thụ lý của cảnh sát Nhật.',
      },
      {
        step: 3,
        title: 'Nộp hồ sơ về ĐSQ / TLSQ có thẩm quyền',
        desc: 'Gửi bưu điện đảm bảo hoặc nộp trực tiếp. Lưu ý giữ lại biên lai bưu điện.',
      },
      {
        step: 4,
        title: 'Chờ xác minh & Nhận hộ chiếu mới',
        desc: 'Cơ quan đại diện sẽ đối chiếu cơ sở dữ liệu xuất nhập cảnh Bộ Công an và trả kết quả.',
      },
    ],
    official_sources: [
      {
        title: 'Đại sứ quán Việt Nam tại Nhật Bản - Cấp hộ chiếu do bị mất',
        url: 'https://vnembassy-jp.org/vi/cap-lai-ho-chieu-do-bi-mat-hong',
      },
    ],
  },
  {
    id: 'vn_passport_damaged',
    category: 'passport',
    title: {
      vi: 'Cấp lại hộ chiếu do bị hư hỏng, rách, ướt',
      en: 'Replacement of Damaged Passport',
      ja: '汚損・破損による一般旅券の再発給',
    },
    summary: 'Áp dụng cho trường hợp hộ chiếu bị ướt, rách trang, lem mực, mờ ảnh hoặc chip bị hỏng không đọc được.',
    when_needed: 'Khi hộ chiếu bị hư hỏng làm giảm giá trị sử dụng hoặc không được hải quan chấp nhận.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 10 ngày làm việc',
    formId: 'form_passport_tk02',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['hộ chiếu bị ướt', 'hộ chiếu bị rách', 'hỏng passport', 'chó cắn passport'],
    related_jp_procedures: ['status-change-guide-jp'],
    required_documents: [
      {
        name: 'Tờ khai đề nghị cấp hộ chiếu (Mẫu TK02)',
        quantity: '01 bản gốc',
        originalOrCopy: 'Gốc',
        note: 'Chọn mục hư hỏng',
        isForm: true,
        formId: 'form_passport_tk02',
      },
      {
        name: 'Hộ chiếu gốc bị hư hỏng',
        quantity: '01 cuốn',
        originalOrCopy: 'Gốc',
        note: 'Nộp lại toàn bộ các phần còn lại của hộ chiếu bị hỏng',
      },
      {
        name: 'Ảnh thẻ chuẩn quốc tế (4x6 cm)',
        quantity: '02 ảnh',
        originalOrCopy: 'Gốc',
        note: 'Nền trắng, chuẩn ICAO',
      },
      {
        name: 'Thẻ ngoại kiều (Zairyu Card)',
        quantity: '01 bản photo',
        originalOrCopy: 'Photo',
        note: 'Sao y 2 mặt',
      },
      {
        name: 'Bì thư Letter Pack Plus đỏ',
        quantity: '01 bì thư',
        originalOrCopy: 'Gốc',
      },
    ],
    steps: [
      { step: 1, title: 'Điền form TK02 trên Toolio', desc: 'Chọn lý do cấp lại do hư hỏng.' },
      { step: 2, title: 'Đóng gói hộ chiếu hỏng cùng ảnh và giấy tờ', desc: 'Không tự ý bóc tách các trang còn lại.' },
      { step: 3, title: 'Gửi bưu điện hoặc nộp tại ĐSQ/TLSQ', desc: 'Nhận hộ chiếu mới sau khi xử lý.' },
    ],
    official_sources: [
      {
        title: 'ĐSQ VN tại Nhật Bản - Cấp lại hộ chiếu hỏng',
        url: 'https://vnembassy-jp.org/vi/cap-lai-ho-chieu-do-bi-mat-hong',
      },
    ],
  },
  {
    id: 'vn_travel_document',
    category: 'passport',
    title: {
      vi: 'Cấp Giấy thông hành về nước khẩn cấp',
      en: 'Emergency Travel Document (Giấy Thông Hành)',
      ja: '緊急帰国渡航書の申請',
    },
    summary: 'Cấp cho công dân Việt Nam không có hộ chiếu (bị mất, chưa được cấp lại kịp) cần về nước khẩn cấp.',
    when_needed: 'Trường hợp có người thân mất, bị trục xuất, hết hạn visa không thể gia hạn hoặc cần về nước gấp không kịp làm hộ chiếu mới.',
    submission_mode: 'direct_only',
    processing_time: 'Trong vòng 2 - 5 ngày làm việc (trường hợp đặc biệt có thể giải quyết trong 24h)',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['giấy thông hành', 'về nước gấp', 'mất hộ chiếu về nước', 'travel document'],
    related_jp_procedures: ['leaving-japan-wizard-jp'],
    required_documents: [
      { name: 'Đơn xin cấp Giấy thông hành', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Theo mẫu của cơ quan đại diện' },
      { name: 'Ảnh 4x6 cm', quantity: '02 ảnh', originalOrCopy: 'Gốc', note: 'Nền trắng' },
      { name: 'Đơn báo mất hộ chiếu có xác nhận của Cảnh sát Nhật', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Nếu mất hộ chiếu' },
      { name: 'Vé máy bay về Việt Nam', quantity: '01 bản', originalOrCopy: 'Bản in/Copy', note: 'Chứng minh nhu cầu xuất cảnh khẩn cấp' },
      { name: 'Giấy tờ chứng minh quốc tịch Việt Nam', quantity: '01 bản', originalOrCopy: 'Gốc hoặc Photo', note: 'CCCD, bản sao khai sinh, hoặc hộ chiếu cũ photo' },
    ],
    steps: [
      { step: 1, title: 'Liên hệ trước đường dây nóng bảo hộ công dân', desc: 'Thông báo tình trạng khẩn cấp và đặt lịch hẹn ưu tiên.' },
      { step: 2, title: 'Có mặt trực tiếp tại ĐSQ/TLSQ', desc: 'Mang theo toàn bộ giấy tờ nhân thân và vé máy bay.' },
      { step: 3, title: 'Cấp Giấy thông hành có giá trị sử dụng 1 lần về thẳng Việt Nam', desc: 'Sử dụng giấy này để làm thủ tục xuất cảnh Nhật Bản và nhập cảnh Việt Nam.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp giấy thông hành', url: 'https://vnembassy-jp.org/vi/cap-giay-thong-hanh' },
    ],
  },
  {
    id: 'vn_passport_child',
    category: 'passport',
    title: {
      vi: 'Cấp hộ chiếu lần đầu cho trẻ em sinh ra tại Nhật Bản',
      en: 'First Passport for Child Born in Japan',
      ja: '日本生まれの児童に対する初回旅券発給',
    },
    summary: 'Cấp hộ chiếu Việt Nam lần đầu cho trẻ em sinh ra tại Nhật Bản (sau khi đã hoàn tất thủ tục đăng ký khai sinh tại ĐSQ/TLSQ).',
    when_needed: 'Khi trẻ em cần có hộ chiếu riêng để làm thủ tục cư trú tại Cục Xuất nhập cảnh Nhật Bản hoặc xuất cảnh về thăm quê.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 10 ngày làm việc (thường làm đồng thời với thủ tục Khai sinh)',
    formId: 'form_passport_tk02',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['làm hộ chiếu cho bé', 'hộ chiếu trẻ em sinh ở nhật', 'passport em bé', 'hộ chiếu sơ sinh'],
    related_jp_procedures: ['child-allowance-jp', 'status-change-guide-jp'],
    required_documents: [
      { name: 'Tờ khai đề nghị cấp hộ chiếu (Mẫu TK02)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Cha hoặc mẹ ký tên thay cho con', isForm: true, formId: 'form_passport_tk02' },
      { name: 'Bản sao Trích lục Giấy khai sinh Việt Nam', quantity: '01 bản', originalOrCopy: 'Bản sao hợp lệ', note: 'Do ĐSQ/TLSQ vừa cấp hoặc cấp trích lục' },
      { name: 'Ảnh thẻ của bé (4x6 cm)', quantity: '02 ảnh', originalOrCopy: 'Gốc', note: 'Chụp rõ mặt, mắt mở, phông nền trắng' },
      { name: 'Bản photo hộ chiếu và thẻ ngoại kiều của cả cha và mẹ', quantity: '01 bộ', originalOrCopy: 'Photo', note: 'Trang thông tin hộ chiếu và 2 mặt thẻ Zairyu' },
      { name: 'Bì thư Letter Pack Plus đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Làm đồng thời với thủ tục Đăng ký khai sinh', desc: 'Có thể nộp cùng lúc bộ hồ sơ khai sinh và cấp hộ chiếu để tiết kiệm thời gian.' },
      { step: 2, title: 'Điền form TK02 phần người nộp thay', desc: 'Cha/mẹ điền thông tin trẻ vào phần người được cấp và ký tên tại mục cha/mẹ.' },
      { step: 3, title: 'Nhận kết quả Giấy khai sinh gốc kèm Hộ chiếu của bé', desc: 'Đem hộ chiếu của bé đến Cục Xuất nhập cảnh Nhật để dán tem tư cách lưu trú (trong vòng 30 ngày từ khi sinh).' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp hộ chiếu lần đầu cho trẻ em', url: 'https://vnembassy-jp.org/vi/cap-ho-chieu-lan-dau-cho-nguoi-chua-tung-duoc-cap-ho-chieu-viet-nam' },
    ],
  },

  // 2. Nhóm Khai sinh & Quốc tịch
  {
    id: 'vn_birth_registration',
    category: 'birth_nationality',
    title: {
      vi: 'Đăng ký khai sinh lần đầu cho con sinh tại Nhật Bản',
      en: 'Consular Birth Registration for Child Born in Japan',
      ja: '日本生まれの児童に対する出生届出（領事出生登録）',
    },
    summary: 'Đăng ký khai sinh và cấp Giấy khai sinh Việt Nam bản gốc cho con sinh ra tại Nhật Bản có cha mẹ là người Việt Nam.',
    when_needed: 'Sau khi sinh con tại bệnh viện Nhật và đã báo sinh tại Shiyakusho/Kuyakusho trong vòng 14 ngày.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 10 ngày làm việc',
    formId: 'form_birth_registration',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['làm giấy khai sinh ở nhật', 'khai sinh cho con', 'đăng ký khai sinh dsq', 'shusseitodoke', 'giấy khai sinh việt nam'],
    related_jp_procedures: ['child-allowance-jp', 'certificate-acquisition-guide-jp'],
    required_documents: [
      { name: 'Tờ khai đăng ký khai sinh (theo Thông tư 04/2020/TT-BTP)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Điền và in từ Toolio', isForm: true, formId: 'form_birth_registration' },
      { name: 'Văn bản thỏa thuận lựa chọn quốc tịch cho con', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Cả cha và mẹ cùng ký chọn quốc tịch Việt Nam', isForm: true, formId: 'form_nationality_agreement' },
      { name: 'Giấy chứng nhận thụ lý báo sinh Nhật Bản (Shussei Todoke Juri Shomeisho)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Do Shiyakusho/Kuyakusho cấp (cấp trong vòng 3 tháng)', isOfficialRequirement: true },
      { name: 'Bản dịch tiếng Việt Giấy chứng nhận thụ lý báo sinh', quantity: '01 bản', originalOrCopy: 'Bản dịch', note: 'Dịch thuật chính xác theo mẫu quy định' },
      { name: 'Giấy chứng nhận kết hôn của cha mẹ', quantity: '01 bản photo', originalOrCopy: 'Photo kèm gốc đối chiếu', note: 'Trường hợp sinh con trong giá thú' },
      { name: 'Hộ chiếu và Thẻ ngoại kiều của cha và mẹ', quantity: '01 bộ photo', originalOrCopy: 'Photo', note: 'Trang thông tin hộ chiếu và 2 mặt thẻ Zairyu' },
      { name: 'Bì thư Letter Pack Plus đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Hoàn tất thủ tục báo sinh tại Shiyakusho/Kuyakusho Nhật', desc: 'Trong vòng 14 ngày sau sinh, nộp Giấy chứng sinh (Shussei Shomeisho) do bệnh viện cấp tại tòa thị chính địa phương và xin ngay "Giấy chứng nhận thụ lý báo sinh" (Shussei Todoke Juri Shomeisho).' },
      { step: 2, title: 'Điền Tờ khai khai sinh và Thỏa thuận quốc tịch trên Toolio', desc: 'Sử dụng Toolio Easy Fill để chuẩn bị hồ sơ song ngữ và mẫu văn bản thỏa thuận chọn quốc tịch cho con.' },
      { step: 3, title: 'Gửi bưu điện đảm bảo về ĐSQ/TLSQ theo thẩm quyền', desc: 'Đính kèm Shussei Todoke Juri Shomeisho bản gốc và bản dịch tiếng Việt.' },
      { step: 4, title: 'Nhận Giấy khai sinh bản chính và trích lục', desc: 'Cơ quan đại diện ghi vào Sổ đăng ký khai sinh và cấp 01 bản chính Giấy khai sinh cùng các bản sao trích lục.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Đăng ký khai sinh', url: 'https://vnembassy-jp.org/vi/dang-ky-khai-sinh' },
      { title: 'TLSQ VN tại Osaka - Hướng dẫn thủ tục khai sinh', url: 'https://vnconsulate-osaka.org/vi/dang-ky-khai-sinh' },
    ],
  },
  {
    id: 'vn_nationality_agreement',
    category: 'birth_nationality',
    title: {
      vi: 'Văn bản thỏa thuận lựa chọn quốc tịch cho con',
      en: 'Agreement on Choice of Nationality for Child',
      ja: '子の国籍選択合意書',
    },
    summary: 'Văn bản bắt buộc lập khi đăng ký khai sinh cho trẻ em có cha hoặc mẹ là công dân nước ngoài, hoặc cả hai cha mẹ thỏa thuận chọn quốc tịch Việt Nam.',
    when_needed: 'Nộp kèm trong hồ sơ đăng ký khai sinh cho con sinh ra tại nước ngoài theo Luật Quốc tịch Việt Nam.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Xử lý đồng thời với hồ sơ Khai sinh',
    formId: 'form_nationality_agreement',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['thỏa thuận quốc tịch', 'chọn quốc tịch cho con', 'quốc tịch việt nam cho bé', 'văn bản quốc tịch'],
    related_jp_procedures: ['child-allowance-jp'],
    required_documents: [
      { name: 'Văn bản thỏa thuận chọn quốc tịch Việt Nam', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Có đầy đủ chữ ký của cha và mẹ', isForm: true, formId: 'form_nationality_agreement' },
      { name: 'Hộ chiếu của cha và mẹ', quantity: '01 bản photo', originalOrCopy: 'Photo' },
    ],
    steps: [
      { step: 1, title: 'Điền thông tin hai bên cha mẹ trên Toolio', desc: 'Nhập thông tin CCCD/Hộ chiếu của cha và mẹ.' },
      { step: 2, title: 'Ký tên xác nhận cam kết đồng thuận', desc: 'Cả hai phụ huynh cùng ký và ghi rõ họ tên.' },
    ],
    official_sources: [
      { title: 'Bộ Tư pháp - Hướng dẫn Luật Quốc tịch', url: 'https://moj.gov.vn' },
    ],
  },
  {
    id: 'vn_birth_extract',
    category: 'birth_nationality',
    title: {
      vi: 'Cấp bản sao trích lục Giấy khai sinh',
      en: 'Issuance of Birth Certificate Copy (Extract)',
      ja: '出生証明書抄本（謄本）の発給',
    },
    summary: 'Cấp bản sao trích lục khai sinh cho người đã từng đăng ký khai sinh tại Cơ quan đại diện Việt Nam tại Nhật Bản.',
    when_needed: 'Khi cần thêm bản sao trích lục khai sinh để nộp cơ quan Nhật hoặc làm hồ sơ du học, định cư.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 3 - 5 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['xin trích lục khai sinh', 'xin lại giấy khai sinh', 'bản sao khai sinh', 'trích lục hộ tịch'],
    related_jp_procedures: ['certificate-acquisition-guide-jp'],
    required_documents: [
      { name: 'Tờ khai cấp bản sao trích lục hộ tịch', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Theo mẫu của Bộ Tư pháp' },
      { name: 'Bản photo Giấy khai sinh cũ (nếu có)', quantity: '01 bản', originalOrCopy: 'Photo', note: 'Ghi rõ số quyển và số vào sổ hộ tịch' },
      { name: 'Hộ chiếu / CCCD của người yêu cầu', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Tra cứu thông tin sổ hộ tịch đã đăng ký', desc: 'Xác định thời điểm đã đăng ký khai sinh tại ĐSQ hay TLSQ nào.' },
      { step: 2, title: 'Gửi hồ sơ yêu cầu trích lục', desc: 'Đính kèm lệ phí và bì thư nhận kết quả.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp trích lục hộ tịch', url: 'https://vnembassy-jp.org/vi/cap-ban-sao-trich-luc-ho-tich' },
    ],
  },

  // 3. Nhóm Hôn nhân & Gia đình
  {
    id: 'vn_marriage_transcription',
    category: 'marriage_family',
    title: {
      vi: 'Ghi chú việc kết hôn (đã kết hôn tại cơ quan Nhật Bản)',
      en: 'Transcription of Marriage Registered in Japan',
      ja: '日本方式で成立した婚姻の報告届（領事婚姻記録）',
    },
    summary: 'Áp dụng cho công dân Việt Nam đã đăng ký kết hôn hợp pháp tại Shiyakusho/Kuyakusho của Nhật Bản, cần ghi chú vào Sổ hộ tịch Việt Nam để được pháp luật Việt Nam công nhận.',
    when_needed: 'Sau khi đã nộp Kon-in Todoke tại cơ quan hộ tịch Nhật Bản và nhận được Giấy chứng nhận thụ lý kết hôn.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 10 ngày làm việc',
    formId: 'form_marriage_registration',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['ghi chú kết hôn', 'báo kết hôn về vn', 'konintodoke', 'công nhận kết hôn nhật', 'đăng ký kết hôn với người nhật'],
    related_jp_procedures: ['status-change-guide-jp'],
    required_documents: [
      { name: 'Tờ khai ghi chú kết hôn', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Điền từ Toolio', isForm: true, formId: 'form_marriage_registration' },
      { name: 'Giấy chứng nhận thụ lý kết hôn của Nhật Bản (Kon-in Todoke Juri Shomeisho)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Cấp trong vòng 3 tháng gần nhất bởi Shiyakusho/Kuyakusho', isOfficialRequirement: true },
      { name: 'Bản dịch tiếng Việt Giấy chứng nhận thụ lý kết hôn', quantity: '01 bản', originalOrCopy: 'Bản dịch' },
      { name: 'Hộ chiếu của cả hai vợ chồng', quantity: '01 bản photo', originalOrCopy: 'Photo kèm gốc đối chiếu' },
      { name: 'Thẻ ngoại kiều (Zairyu Card) của bên người Việt', quantity: '01 bản photo', originalOrCopy: 'Photo 2 mặt' },
      { name: 'Bì thư Letter Pack Plus đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Xin Kon-in Todoke Juri Shomeisho tại Shiyakusho/Kuyakusho', desc: 'Sau khi hoàn tất thủ tục kết hôn tại Nhật, xin bản chứng nhận thụ lý.' },
      { step: 2, title: 'Điền Tờ khai ghi chú kết hôn trên Toolio', desc: 'Chuẩn bị bản dịch tiếng Việt chuẩn mực.' },
      { step: 3, title: 'Nộp hồ sơ đến ĐSQ/TLSQ', desc: 'Nhận Trích lục ghi chú kết hôn công nhận hôn nhân theo pháp luật Việt Nam.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Ghi chú kết hôn', url: 'https://vnembassy-jp.org/vi/ghi-chu-ket-hon' },
    ],
  },
  {
    id: 'vn_marital_status_certificate',
    category: 'marriage_family',
    title: {
      vi: 'Cấp Giấy xác nhận tình trạng hôn nhân (để kết hôn tại Nhật)',
      en: 'Certificate of Marital Status (For Marriage in Japan)',
      ja: '婚姻要件具備証明書（独身証明書）の発給',
    },
    summary: 'Cấp Giấy chứng nhận đủ điều kiện kết hôn / Giấy xác nhận độc thân cho công dân Việt Nam để nộp cho Tòa thị chính Nhật Bản (Shiyakusho) khi đăng ký kết hôn.',
    when_needed: 'Khi chuẩn bị kết hôn với người Nhật Bản hoặc công dân nước ngoài tại Tòa thị chính Nhật Bản.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 7 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['giấy độc thân', 'kon-in yoken gubi shomeisho', 'chứng nhận độc thân', 'xác nhận tình trạng hôn nhân', 'kết hôn với người nhật'],
    related_jp_procedures: ['certificate-acquisition-guide-jp'],
    required_documents: [
      { name: 'Tờ khai cấp Giấy xác nhận tình trạng hôn nhân', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Theo mẫu của Cơ quan đại diện' },
      { name: 'Giấy xác nhận tình trạng hôn nhân do UBND tại VN cấp', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Cấp cho thời gian cư trú tại VN trước khi sang Nhật' },
      { name: 'Giấy cư trú tại Nhật (Juminhyo)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Ghi rõ tình trạng hộ gia đình, cấp trong vòng 3 tháng' },
      { name: 'Hộ chiếu gốc và Thẻ ngoại kiều', quantity: '01 bộ', originalOrCopy: 'Gốc & Photo' },
      { name: 'Bản photo hộ chiếu / bằng lái xe của người dự định kết hôn', quantity: '01 bản', originalOrCopy: 'Photo' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Xin Giấy xác nhận tình trạng hôn nhân từ UBND xã/phường ở VN', desc: 'Nhờ người nhà xin tại Việt Nam cho khoảng thời gian từ đủ tuổi kết hôn đến khi xuất cảnh sang Nhật.' },
      { step: 2, title: 'Xin Juminhyo tại Shiyakusho nơi cư trú', desc: 'Có ghi mục tình trạng độc thân/hộ gia đình.' },
      { step: 3, title: 'Nộp hồ sơ đến ĐSQ/TLSQ', desc: 'ĐSQ cấp Giấy Kon-in Yoken Gubi Shomeisho bằng tiếng Nhật/tiếng Việt để nộp Shiyakusho.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp giấy chứng nhận đủ điều kiện kết hôn', url: 'https://vnembassy-jp.org/vi/cap-giay-xac-nhan-tinh-trang-hon-nhan' },
    ],
  },
  {
    id: 'vn_marriage_certificate_dsq',
    category: 'marriage_family',
    title: {
      vi: 'Đăng ký kết hôn trực tiếp tại Cơ quan đại diện (hai công dân VN)',
      en: 'Direct Consular Marriage Registration (Both Vietnamese Citizens)',
      ja: '領事館での直接婚姻届出（当事者双方ベトナム人）',
    },
    summary: 'Đăng ký kết hôn cho hai công dân Việt Nam cùng cư trú tại Nhật Bản trực tiếp tại ĐSQ/TLSQ Việt Nam.',
    when_needed: 'Khi cả hai bên nam và nữ đều là công dân Việt Nam muốn được cấp Giấy chứng nhận kết hôn của Việt Nam trực tiếp tại Nhật.',
    submission_mode: 'direct_only',
    processing_time: 'Khoảng 10 - 15 ngày làm việc (hai bên bắt buộc phải có mặt ký vào Sổ kết hôn)',
    formId: 'form_marriage_registration',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['kết hôn tại dsq', 'kết hôn 2 người việt ở nhật', 'làm giấy kết hôn', 'đăng ký kết hôn'],
    related_jp_procedures: ['status-change-guide-jp'],
    required_documents: [
      { name: 'Tờ khai đăng ký kết hôn', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Hai bên cùng ký', isForm: true, formId: 'form_marriage_registration' },
      { name: 'Giấy xác nhận tình trạng hôn nhân của cả hai bên', quantity: '02 bản gốc', originalOrCopy: 'Gốc', note: 'Do UBND xã/phường tại VN cấp' },
      { name: 'Giấy khám sức khỏe tâm thần', quantity: '02 bản gốc', originalOrCopy: 'Gốc', note: 'Do bệnh viện có thẩm quyền cấp xác nhận có đủ năng lực hành vi dân sự' },
      { name: 'Hộ chiếu gốc và Thẻ ngoại kiều của hai bên', quantity: '02 bộ', originalOrCopy: 'Gốc & Photo' },
    ],
    steps: [
      { step: 1, title: 'Chuẩn bị đầy đủ giấy xác nhận độc thân và khám sức khỏe', desc: 'Có đầy đủ giấy tờ hợp lệ từ VN và Nhật Bản.' },
      { step: 2, title: 'Đặt lịch hẹn và có mặt trực tiếp tại ĐSQ/TLSQ', desc: 'Cả hai bên nam nữ bắt buộc phải có mặt.' },
      { step: 3, title: 'Ký vào Sổ hộ tịch và Giấy chứng nhận kết hôn', desc: 'Viên chức lãnh sự trao Giấy chứng nhận kết hôn bản chính cho hai vợ chồng.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Đăng ký kết hôn', url: 'https://vnembassy-jp.org/vi/thu-tuc-dang-ky-ket-hon-tai-dai-su-quan' },
    ],
  },

  // 4. Nhóm Hợp pháp hóa & Chứng thực
  {
    id: 'vn_consular_legalization_jp_docs',
    category: 'legalization_auth',
    title: {
      vi: 'Hợp pháp hóa lãnh sự giấy tờ Nhật Bản để sử dụng tại Việt Nam',
      en: 'Consular Legalization of Japanese Documents for Use in Vietnam',
      ja: 'ベトナム提出用日本の公文書に対する領事認証',
    },
    summary: 'Xác thực con dấu và chữ ký của Bộ Ngoại giao Nhật Bản (MOFA Japan) trên các giấy tờ của Nhật Bản (bằng cấp, giấy tờ công ty, giấy khai sinh Nhật...) để sử dụng hợp pháp tại Việt Nam.',
    when_needed: 'Khi cần mang giấy tờ do cơ quan/trường học Nhật Bản cấp về Việt Nam làm thủ tục xin việc, giấy phép lao động, kết hôn, hoặc định cư.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 3 - 5 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['hợp pháp hóa lãnh sự', 'chứng nhận gaimusho', 'chứng nhận mofa', 'hợp pháp hóa bằng cấp', 'dấu lãnh sự'],
    related_jp_procedures: ['leaving-japan-wizard-jp'],
    required_documents: [
      { name: 'Bản gốc giấy tờ đã được Bộ Ngoại giao Nhật Bản (MOFA Japan / Gaimusho) chứng nhận', quantity: '01 bản gốc', originalOrCopy: 'Gốc kèm tem chứng nhận của MOFA', isOfficialRequirement: true },
      { name: 'Bản photo toàn bộ giấy tờ đã có dấu của MOFA', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Tờ khai đề nghị hợp pháp hóa lãnh sự', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Theo mẫu của Cơ quan đại diện' },
      { name: 'Hộ chiếu / Thẻ ngoại kiều của người nộp', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Xin chứng nhận tại Bộ Ngoại giao Nhật Bản (Gaimusho / 外務省)', desc: 'Gửi giấy tờ đến Gaimusho (Tokyo hoặc Osaka) để xin con dấu chứng nhận công hàm (Koushinin / Koubunsho Ninshou).' },
      { step: 2, title: 'Chuẩn bị hồ sơ nộp đến ĐSQ/TLSQ Việt Nam', desc: 'Đính kèm bản gốc đã có tem Gaimusho và bản photo.' },
      { step: 3, title: 'Nhận giấy tờ đã dán tem Hợp pháp hóa lãnh sự Việt Nam', desc: 'Giấy tờ sau khi được dán tem có giá trị pháp lý đầy đủ tại Việt Nam.' },
    ],
    official_sources: [
      { title: 'Bộ Ngoại giao Nhật Bản - Hướng dẫn Apostille / Công nhận công văn', url: 'https://www.mofa.go.jp/mofaj/toko/todoke/shomei/index.html' },
      { title: 'ĐSQ VN tại Nhật Bản - Hợp pháp hóa lãnh sự', url: 'https://vnembassy-jp.org/vi/hop-phap-hoa-va-chung-thuc-chu-ky' },
    ],
  },
  {
    id: 'vn_signature_authentication',
    category: 'legalization_auth',
    title: {
      vi: 'Chứng thực chữ ký trên Giấy ủy quyền / Hợp đồng',
      en: 'Signature Authentication (Power of Attorney)',
      ja: '委任状・契約書等に対する私署証書の署名認証',
    },
    summary: 'Viên chức lãnh sự chứng thực chữ ký của người lập văn bản ủy quyền để giao dịch tại Việt Nam (rút BHXH 1 lần, mua bán nhà đất, rút tiền ngân hàng...).',
    when_needed: 'Khi công dân ở Nhật Bản cần ủy quyền cho người thân ở Việt Nam thực hiện các công việc pháp lý.',
    submission_mode: 'direct_only',
    processing_time: 'Thực hiện và trả kết quả trong ngày làm việc',
    formId: 'form_power_of_attorney',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['chứng thực chữ ký', 'giấy ủy quyền rút bhxh', 'ủy quyền nhà đất', 'chứng thực ủy quyền', 'ký giấy ủy quyền'],
    related_jp_procedures: ['leaving-japan-wizard-jp'],
    required_documents: [
      { name: 'Giấy ủy quyền soạn sẵn chuẩn Nghị định 30/2020/NĐ-CP', quantity: '02 bản gốc', originalOrCopy: 'Gốc', note: 'Chưa ký tên trước (bắt buộc ký trước mặt viên chức lãnh sự)', isForm: true, formId: 'form_power_of_attorney' },
      { name: 'Hộ chiếu gốc và Thẻ ngoại kiều của người ủy quyền', quantity: '01 bộ', originalOrCopy: 'Gốc' },
      { name: 'Bản photo CCCD của người được ủy quyền tại Việt Nam', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Giấy tờ liên quan đến nội dung ủy quyền (sổ đỏ, sổ BHXH, sổ tiết kiệm...)', quantity: '01 bản photo', originalOrCopy: 'Photo' },
    ],
    steps: [
      { step: 1, title: 'Soạn thảo Giấy ủy quyền chuẩn thể thức NĐ 30 trên Toolio', desc: 'Điền đầy đủ thông tin nhân thân hai bên và phạm vi ủy quyền rõ ràng.' },
      { step: 2, title: 'Có mặt trực tiếp tại ĐSQ/TLSQ (KHÔNG KÝ TRƯỚC)', desc: 'Mang theo bản in giấy ủy quyền cùng hộ chiếu gốc.' },
      { step: 3, title: 'Ký tên trước sự chứng kiến của cán bộ lãnh sự', desc: 'Viên chức lãnh sự đối chiếu nhân thân, đóng dấu chứng thực chữ ký và giao trả văn bản.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Chứng thực chữ ký và ủy quyền', url: 'https://vnembassy-jp.org/vi/hop-phap-hoa-va-chung-thuc-chu-ky' },
    ],
  },
  {
    id: 'vn_consular_certification_vn_docs',
    category: 'legalization_auth',
    title: {
      vi: 'Chứng nhận lãnh sự giấy tờ Việt Nam để sử dụng tại Nhật Bản',
      en: 'Consular Certification of Vietnamese Documents for Use in Japan',
      ja: '日本提出用ベトナム公文書に対する領事認証',
    },
    summary: 'Chứng nhận tính xác thực của các văn bản do cơ quan Việt Nam cấp (Lý lịch tư pháp, Khai sinh, Bằng đại học...) để nộp cho cơ quan/doanh nghiệp Nhật.',
    when_needed: 'Khi làm thủ tục xin visa, nhập học, xin việc hoặc làm thủ tục hành chính tại Nhật Bản có yêu cầu xác thực lãnh sự.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 3 - 5 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['chứng nhận lãnh sự', 'xác nhận bằng đại học', 'chứng nhận bằng cấp', 'dấu dsq cho giấy tờ vn'],
    related_jp_procedures: ['status-change-guide-jp'],
    required_documents: [
      { name: 'Bản gốc giấy tờ đã được Cục Lãnh sự Bộ Ngoại giao VN chứng nhận', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
      { name: 'Bản photo giấy tờ', quantity: '01 bản', originalOrCopy: 'Photo' },
      { name: 'Tờ khai chứng nhận lãnh sự', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
      { name: 'Hộ chiếu của người nộp', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Kiểm tra tem chứng nhận của Cục Lãnh sự VN', desc: 'Đảm bảo giấy tờ đã được hợp thức hóa tại Việt Nam trước khi gửi sang ĐSQ tại Nhật.' },
      { step: 2, title: 'Gửi hồ sơ đến ĐSQ/TLSQ', desc: 'Đính kèm phong bì hồi báo.' },
    ],
    official_sources: [
      { title: 'Cổng thông tin Lãnh sự - Bộ Ngoại giao VN', url: 'https://lanhsuvietnam.gov.vn' },
    ],
  },

  // 5. Nhóm Khai tử & Hộ tịch khác
  {
    id: 'vn_death_registration',
    category: 'death_civil',
    title: {
      vi: 'Đăng ký khai tử cho công dân Việt Nam qua đời tại Nhật Bản',
      en: 'Death Registration for Vietnamese Citizens in Japan',
      ja: '在日ベトナム人に対する死亡届出',
    },
    summary: 'Đăng ký khai tử và cấp Trích lục khai tử cho công dân Việt Nam không may qua đời trên lãnh thổ Nhật Bản.',
    when_needed: 'Khi có công dân Việt Nam qua đời tại Nhật Bản sau khi đã hoàn tất thủ tục báo tử tại chính quyền địa phương Nhật.',
    submission_mode: 'direct_or_postal',
    processing_time: 'Giải quyết khẩn cấp trong ngày hoặc 1 - 2 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['khai tử', 'báo tử', 'người việt mất tại nhật', 'giấy báo tử', 'shibotodoke'],
    related_jp_procedures: ['leaving-japan-wizard-jp'],
    required_documents: [
      { name: 'Tờ khai đăng ký khai tử', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Theo mẫu của Bộ Tư pháp' },
      { name: 'Giấy chứng nhận thụ lý báo tử của Nhật Bản (Shibo Todoke Juri Shomeisho) hoặc Giấy chứng tử của Bác sĩ (Shibo Shindansho)', quantity: '01 bản gốc', originalOrCopy: 'Gốc', isOfficialRequirement: true },
      { name: 'Bản dịch tiếng Việt Giấy chứng tử', quantity: '01 bản', originalOrCopy: 'Bản dịch' },
      { name: 'Hộ chiếu gốc và Thẻ ngoại kiều của người đã mất', quantity: '01 bộ', originalOrCopy: 'Gốc', note: 'Nộp lại để thu hồi hủy giá trị' },
      { name: 'Giấy tờ tùy thân của người đi khai tử', quantity: '01 bản photo', originalOrCopy: 'Photo kèm gốc đối chiếu' },
    ],
    steps: [
      { step: 1, title: 'Báo tử tại Shiyakusho/Kuyakusho của Nhật Bản', desc: 'Nhận Giấy chứng nhận thụ lý báo tử (Shibo Todoke Juri Shomeisho).' },
      { step: 2, title: 'Liên hệ Cơ quan đại diện Việt Nam', desc: 'Nộp hồ sơ để cấp Trích lục khai tử của Việt Nam và hỗ trợ thủ tục mang tro cốt/thi hài về nước.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Thủ tục khai tử', url: 'https://vnembassy-jp.org/vi/thu-tuc-khai-tu' },
    ],
  },
  {
    id: 'vn_death_extract',
    category: 'death_civil',
    title: {
      vi: 'Cấp trích lục bản sao giấy chứng tử',
      en: 'Issuance of Death Extract Copy',
      ja: '死亡証明書抄本（謄本）の発給',
    },
    summary: 'Cấp bản sao trích lục khai tử cho người đã từng đăng ký khai tử tại Cơ quan đại diện Việt Nam tại Nhật Bản.',
    when_needed: 'Để giải quyết thừa kế, nhận tiền bảo hiểm hoặc chế độ tử tuất tại Việt Nam.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 3 - 5 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['trích lục khai tử', 'bản sao giấy báo tử', 'chế độ tử tuất'],
    related_jp_procedures: ['social-insurance-jp'],
    required_documents: [
      { name: 'Tờ khai cấp bản sao trích lục hộ tịch', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
      { name: 'Giấy tờ chứng minh quan hệ thân nhân với người đã mất', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Điền đơn yêu cầu trích lục', desc: 'Kèm theo thông tin người đã mất.' },
      { step: 2, title: 'Nhận kết quả qua bưu điện', desc: 'ĐSQ/TLSQ trả trích lục có dấu đỏ.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp trích lục hộ tịch', url: 'https://vnembassy-jp.org/vi/cap-ban-sao-trich-luc-ho-tich' },
    ],
  },

  // 6. Nhóm Bảo hộ công dân & Khẩn cấp
  {
    id: 'vn_citizen_protection_lost_docs',
    category: 'protection_emergency',
    title: {
      vi: 'Hỗ trợ công dân mất toàn bộ giấy tờ tùy thân tại Nhật',
      en: 'Emergency Assistance for Lost Identification Documents',
      ja: '全身分証紛失時の緊急領事支援',
    },
    summary: 'Quy trình xử lý khẩn cấp khi người Việt Nam bị mất sạch hộ chiếu, thẻ ngoại kiều (Zairyu Card) và tiền mặt tại Nhật.',
    when_needed: 'Bị cướp giật, hỏa hoạn, mất ví hoặc gặp sự cố làm mất toàn bộ giấy tờ nhân thân.',
    submission_mode: 'direct_only',
    processing_time: 'Hỗ trợ ngay lập tức qua Hotline và tại Cơ quan đại diện',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['mất hết giấy tờ', 'mất sạch zairyu card và hộ chiếu', 'cấp cứu lãnh sự', 'bảo hộ khẩn cấp'],
    related_jp_procedures: ['certificate-acquisition-guide-jp'],
    required_documents: [
      { name: 'Biên bản tiếp nhận của Cảnh sát Nhật Bản', quantity: '01 bản', originalOrCopy: 'Gốc' },
      { name: 'Ảnh chân dung', quantity: '02 ảnh', originalOrCopy: 'Gốc' },
      { name: 'Thông tin nhân thân, quê quán tại Việt Nam để đối chiếu hệ thống', quantity: 'Lời khai', originalOrCopy: 'Trực tiếp' },
    ],
    steps: [
      { step: 1, title: 'Gọi ngay số điện thoại Hotline bảo hộ công dân', desc: 'ĐSQ Tokyo: +81-80-3590-9136 | TLSQ Osaka: +81-72-221-6666 | TLSQ Fukuoka: +81-92-263-7668.' },
      { step: 2, title: 'Đến Đồn Cảnh sát (Keisatsusho) trình báo', desc: 'Nhận số thụ lý báo mất đồ (Ibutsu Todokede).' },
      { step: 3, title: 'Đến Cục Xuất nhập cảnh Nhật xin cấp lại Zairyu Card', desc: 'Cục Xuất nhập cảnh cấp lại thẻ ngoại kiều trong ngày làm việc.' },
      { step: 4, title: 'Đến ĐSQ/TLSQ để cấp hộ chiếu mới hoặc giấy thông hành', desc: 'Cơ quan đại diện xác minh và cấp giấy tờ đi lại.' },
    ],
    official_sources: [
      { title: 'Cổng thông tin Bảo hộ Công dân - Bộ Ngoại giao VN', url: 'https://baohocongdan.vn' },
      { title: 'ĐSQ VN tại Nhật Bản - Đường dây nóng bảo hộ công dân', url: 'https://vnembassy-jp.org/vi/duong-day-nong-bao-ho-cong-dan' },
    ],
  },
  {
    id: 'vn_citizen_protection_detained_accident',
    category: 'protection_emergency',
    title: {
      vi: 'Bảo hộ công dân khi bị bắt giữ, tai nạn hoặc bệnh tật hiểm nghèo',
      en: 'Consular Protection in Detention, Accident or Critical Illness',
      ja: '拘束・重大事故・重病時の邦人保護支援',
    },
    summary: 'Các biện pháp bảo vệ quyền lợi hợp pháp, thăm lãnh sự và phối hợp với cơ quan chức năng sở tại khi công dân Việt Nam gặp nạn.',
    when_needed: 'Khi người thân, bạn bè hoặc đồng hương bị cảnh sát Nhật Bản tạm giữ, bị tai nạn lao động nặng hoặc qua đời đột ngột.',
    submission_mode: 'direct_only',
    processing_time: '24/7 qua đường dây nóng bảo hộ công dân',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['bị bắt ở nhật', 'tai nạn lao động', 'thăm gặp lãnh sự', 'bảo hộ công dân khẩn cấp'],
    related_jp_procedures: ['social-insurance-jp'],
    required_documents: [
      { name: 'Đơn đề nghị bảo hộ công dân', quantity: '01 bản', originalOrCopy: 'Bản viết hoặc qua điện thoại/email' },
      { name: 'Thông tin cá nhân người gặp nạn (Họ tên, ngày sinh, số thẻ Zairyu/Hộ chiếu)', quantity: '01 bản', originalOrCopy: 'Photo hoặc bản ghi chép' },
      { name: 'Địa chỉ nơi đang bị giam giữ hoặc bệnh viện đang cấp cứu', quantity: 'Thông tin cụ thể', originalOrCopy: 'Văn bản' },
    ],
    steps: [
      { step: 1, title: 'Liên hệ Tổng đài Bảo hộ công dân toàn cầu (+84 24 3982 9999) hoặc Hotline tại Nhật', desc: 'Cung cấp đầy đủ thông tin nhân thân và địa điểm người gặp nạn.' },
      { step: 2, title: 'Cơ quan đại diện can thiệp ngoại giao', desc: 'Thực hiện quyền thăm lãnh sự, yêu cầu cơ quan Nhật bảo đảm quyền con người, tiếp cận y tế và luật sư bào chữa.' },
      { step: 3, title: 'Phối hợp gia đình và các cơ quan hỗ trợ', desc: 'Hỗ trợ kết nối gia đình sang Nhật trong trường hợp nguy kịch.' },
    ],
    official_sources: [
      { title: 'Cục Lãnh sự - Tổng đài Bảo hộ công dân', url: 'https://lanhsuvietnam.gov.vn' },
    ],
  },

  // 7. Nhóm Miễn thị thực & Thủ tục khác
  {
    id: 'vn_visa_exemption_5yr',
    category: 'visa_other',
    title: {
      vi: 'Cấp Giấy miễn thị thực 5 năm (cho Việt kiều và thân nhân)',
      en: '5-Year Visa Exemption Certificate',
      ja: '5年間有効査証免除証明書の発給',
    },
    summary: 'Cấp Giấy miễn thị thực có giá trị 5 năm cho người Việt Nam định cư tại Nhật Bản hoặc người nước ngoài là vợ, chồng, con của công dân Việt Nam.',
    when_needed: 'Để nhập cảnh Việt Nam nhiều lần trong 5 năm, mỗi lần được tạm trú tối đa 6 tháng mà không cần xin visa.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 5 - 7 ngày làm việc',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['miễn thị thực 5 năm', 'visa 5 năm', 'về việt nam không cần visa', 'miễn visa cho vợ chồng con'],
    related_jp_procedures: ['leaving-japan-wizard-jp'],
    required_documents: [
      { name: 'Tờ khai đề nghị cấp Giấy miễn thị thực (Mẫu NA9)', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
      { name: 'Ảnh 4x6 cm', quantity: '02 ảnh', originalOrCopy: 'Gốc', note: 'Nền trắng, mắt nhìn thẳng' },
      { name: 'Hộ chiếu nước ngoài (còn hạn ít nhất 1 năm)', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
      { name: 'Giấy tờ chứng minh gốc Việt Nam hoặc quan hệ thân nhân', quantity: '01 bản photo kèm gốc', originalOrCopy: 'Bản sao/Photo', note: 'Khai sinh, Giấy kết hôn, Hộ chiếu VN cũ...' },
      { name: 'Bì thư Letter Pack đỏ', quantity: '01 bì thư', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Điền form Mẫu NA9', desc: 'Khai báo thông tin người được cấp và người bảo lãnh.' },
      { step: 2, title: 'Nộp hồ sơ đến ĐSQ hoặc TLSQ', desc: 'Kèm hộ chiếu nước ngoài bản gốc.' },
      { step: 3, title: 'Nhận Giấy miễn thị thực 5 năm', desc: 'Được dán trực tiếp vào hộ chiếu hoặc cấp dạng sổ rời.' },
    ],
    official_sources: [
      { title: 'ĐSQ VN tại Nhật Bản - Cấp giấy miễn thị thực 5 năm', url: 'https://vnembassy-jp.org/vi/cap-giay-mien-thi-thuc-5-nam' },
    ],
  },
  {
    id: 'vn_criminal_record_support',
    category: 'visa_other',
    title: {
      vi: 'Hướng dẫn xin Phiếu Lý lịch tư pháp Việt Nam từ Nhật Bản',
      en: 'Support for Obtaining Vietnam Criminal Record (LLTP) from Japan',
      ja: '日本からのベトナム無犯罪証明書（司法履歴書）取得案内',
    },
    summary: 'Hướng dẫn thủ tục ủy quyền cho người thân tại Việt Nam hoặc làm thủ tục trực tuyến trên Cổng dịch vụ công quốc gia để xin Phiếu Lý lịch tư pháp số 1 hoặc số 2.',
    when_needed: 'Khi chuyển đổi tư cách lưu trú sang Vĩnh trú (Eijyu), xin quốc tịch Nhật, hoặc xin việc làm đòi hỏi lý lịch trong sạch.',
    submission_mode: 'postal_or_direct',
    processing_time: 'Khoảng 15 - 20 ngày làm việc (do Sở Tư pháp hoặc Trung tâm LLTP quốc gia tại VN xử lý)',
    formId: 'form_power_of_attorney',
    status: 'VERIFIED',
    last_verified: '2026-09-01',
    aliases: ['lý lịch tư pháp', 'phiếu lý lịch tư pháp số 2', 'xin lltp ở nhật', 'hồ sơ vĩnh trú', 'giấy không tiền án tiền sự'],
    related_jp_procedures: ['pr-readiness-checker-jp', 'status-change-guide-jp'],
    required_documents: [
      { name: 'Giấy ủy quyền xin Lý lịch tư pháp', quantity: '01 bản gốc', originalOrCopy: 'Gốc', note: 'Có chứng thực chữ ký tại ĐSQ/TLSQ', isForm: true, formId: 'form_power_of_attorney' },
      { name: 'Bản sao CCCD của người yêu cầu và người được ủy quyền', quantity: '01 bản photo', originalOrCopy: 'Photo' },
      { name: 'Tờ khai yêu cầu cấp Phiếu Lý lịch tư pháp', quantity: '01 bản gốc', originalOrCopy: 'Gốc' },
    ],
    steps: [
      { step: 1, title: 'Lập Giấy ủy quyền chuẩn NĐ 30 trên Toolio', desc: 'Ủy quyền cho cha/mẹ/vợ/chồng/con ở Việt Nam nộp hồ sơ xin LLTP.' },
      { step: 2, title: 'Đến ĐSQ/TLSQ chứng thực chữ ký', desc: 'Viên chức lãnh sự chứng nhận chữ ký trên Giấy ủy quyền.' },
      { step: 3, title: 'Gửi Giấy ủy quyền về Việt Nam', desc: 'Người nhà tại Việt Nam mang đến Trung tâm Phục vụ Hành chính công tỉnh/thành phố để nhận kết quả.' },
    ],
    official_sources: [
      { title: 'Cổng Dịch vụ công Quốc gia - Cấp Phiếu Lý lịch tư pháp', url: 'https://dichvucong.gov.vn' },
      { title: 'Trung tâm Lý lịch tư pháp Quốc gia', url: 'https://ttlltpqg.moj.gov.vn' },
    ],
  },
];

export const CONSULAR_PROCEDURE_MAP = new Map(
  CONSULAR_PROCEDURES.map((p) => [p.id, p])
);

export const getProcedureById = (id) => CONSULAR_PROCEDURE_MAP.get(id) || null;

export const getProceduresByCategory = (catId) =>
  CONSULAR_PROCEDURES.filter((p) => p.category === catId);
