/**
 * @file packages/core/src/utils/screen-recorder/ebmlPatcher.js
 * ============================================================================
 * Zero-dependency EBML metadata patcher for WebM recordings.
 * Fixes missing Duration metadata generated by MediaRecorder in Chromium/Firefox,
 * enabling seamless video seeking/scrubbing and accurate duration display.
 * ============================================================================
 */

/*
 * List of possible WebM EBML file sections by their IDs.
 */
const sections = {
  0xa45dfa3: { name: 'EBML', type: 'Container' },
  0x286: { name: 'EBMLVersion', type: 'Uint' },
  0x2f7: { name: 'EBMLReadVersion', type: 'Uint' },
  0x2f2: { name: 'EBMLMaxIDLength', type: 'Uint' },
  0x2f3: { name: 'EBMLMaxSizeLength', type: 'Uint' },
  0x282: { name: 'DocType', type: 'String' },
  0x287: { name: 'DocTypeVersion', type: 'Uint' },
  0x285: { name: 'DocTypeReadVersion', type: 'Uint' },
  0x6c: { name: 'Void', type: 'Binary' },
  0x3f: { name: 'CRC-32', type: 'Binary' },
  0x8538067: { name: 'Segment', type: 'Container' },
  0x14d9b74: { name: 'SeekHead', type: 'Container' },
  0xdbb: { name: 'Seek', type: 'Container' },
  0x13ab: { name: 'SeekID', type: 'Binary' },
  0x13ac: { name: 'SeekPosition', type: 'Uint' },
  0x549a966: { name: 'Info', type: 'Container' },
  0xad7b1: { name: 'TimecodeScale', type: 'Uint' },
  0x489: { name: 'Duration', type: 'Float' },
  0x461: { name: 'DateUTC', type: 'Date' },
  0x3ba9: { name: 'Title', type: 'String' },
  0xd80: { name: 'MuxingApp', type: 'String' },
  0x1741: { name: 'WritingApp', type: 'String' },
  0x654ae6b: { name: 'Tracks', type: 'Container' },
  0x2e: { name: 'TrackEntry', type: 'Container' },
  0x57: { name: 'TrackNumber', type: 'Uint' },
  0x33c5: { name: 'TrackUID', type: 'Uint' },
  0x3: { name: 'TrackType', type: 'Uint' },
  0x60: { name: 'Video', type: 'Container' },
  0x61: { name: 'Audio', type: 'Container' }
};

function padHex(hex) {
  return hex.length % 2 === 1 ? '0' + hex : hex;
}

class WebmBase {
  constructor(name = 'Unknown', type = 'Unknown') {
    this.name = name;
    this.type = type;
  }
  updateBySource() {}
  setSource(source) {
    this.source = source;
    this.updateBySource();
  }
  updateByData() {}
  setData(data) {
    this.data = data;
    this.updateByData();
  }
}

class WebmUint extends WebmBase {
  constructor(name, type = 'Uint') {
    super(name, type);
  }
  updateBySource() {
    this.data = '';
    for (let i = 0; i < this.source.length; i++) {
      const hex = this.source[i].toString(16);
      this.data += padHex(hex);
    }
  }
  updateByData() {
    const length = this.data.length / 2;
    this.source = new Uint8Array(length);
    for (let i = 0; i < length; i++) {
      const hex = this.data.substr(i * 2, 2);
      this.source[i] = parseInt(hex, 16);
    }
  }
  getValue() {
    return parseInt(this.data, 16);
  }
  setValue(value) {
    this.setData(padHex(value.toString(16)));
  }
}

class WebmFloat extends WebmBase {
  constructor(name, type = 'Float') {
    super(name, type);
  }
  getFloatArrayType() {
    return this.source && this.source.length === 4 ? Float32Array : Float64Array;
  }
  updateBySource() {
    const byteArray = new Uint8Array(this.source).reverse();
    const FloatArrayType = this.getFloatArrayType();
    const floatArray = new FloatArrayType(byteArray.buffer);
    this.data = floatArray[0];
  }
  updateByData() {
    const FloatArrayType = this.getFloatArrayType();
    const floatArray = new FloatArrayType([this.data]);
    const byteArray = new Uint8Array(floatArray.buffer);
    this.source = byteArray.reverse();
  }
  getValue() {
    return this.data;
  }
  setValue(value) {
    this.setData(value);
  }
}

class WebmContainer extends WebmBase {
  constructor(name, type = 'Container') {
    super(name, type);
    this.offset = 0;
  }
  readByte() {
    return this.source[this.offset++];
  }
  readUint() {
    const firstByte = this.readByte();
    const bytes = 8 - firstByte.toString(2).length;
    let value = firstByte - (1 << (7 - bytes));
    for (let i = 0; i < bytes; i++) {
      value *= 256;
      value += this.readByte();
    }
    return value;
  }
  updateBySource() {
    this.data = [];
    for (this.offset = 0; this.offset < this.source.length; ) {
      const id = this.readUint();
      const len = this.readUint();
      const end = Math.min(this.offset + len, this.source.length);
      const data = this.source.slice(this.offset, end);

      const info = sections[id] || { name: 'Unknown', type: 'Unknown' };
      let SectionClass = WebmBase;
      if (info.type === 'Container') SectionClass = WebmContainer;
      else if (info.type === 'Uint') SectionClass = WebmUint;
      else if (info.type === 'Float') SectionClass = WebmFloat;

      const section = new SectionClass(info.name, info.type);
      section.setSource(data);
      this.data.push({
        id: id,
        idHex: id.toString(16),
        data: section
      });
      this.offset = end;
    }
  }
  writeUint(x, draft) {
    let bytes = 1;
    let flag = 0x80;
    while (x >= flag && bytes < 8) {
      bytes++;
      flag *= 0x80;
    }
    if (!draft) {
      let value = flag + x;
      for (let i = bytes - 1; i >= 0; i--) {
        const c = value % 256;
        this.source[this.offset + i] = c;
        value = (value - c) / 256;
      }
    }
    this.offset += bytes;
  }
  writeSections(draft) {
    this.offset = 0;
    for (let i = 0; i < this.data.length; i++) {
      const section = this.data[i];
      const content = section.data.source;
      const contentLength = content.length;
      this.writeUint(section.id, draft);
      this.writeUint(contentLength, draft);
      if (!draft) {
        this.source.set(content, this.offset);
      }
      this.offset += contentLength;
    }
    return this.offset;
  }
  updateByData() {
    const length = this.writeSections('draft');
    this.source = new Uint8Array(length);
    this.writeSections();
  }
  getSectionById(id) {
    for (let i = 0; i < this.data.length; i++) {
      if (this.data[i].id === id) {
        return this.data[i].data;
      }
    }
    return null;
  }
}

class WebmFile extends WebmContainer {
  constructor(source) {
    super('File', 'File');
    this.setSource(source);
  }
  fixDuration(duration) {
    const segmentSection = this.getSectionById(0x8538067);
    if (!segmentSection) return false;

    const infoSection = segmentSection.getSectionById(0x549a966);
    if (!infoSection) return false;

    const timeScaleSection = infoSection.getSectionById(0xad7b1);
    if (!timeScaleSection) return false;

    let durationSection = infoSection.getSectionById(0x489);
    if (durationSection) {
      if (durationSection.getValue() <= 0) {
        durationSection.setValue(duration);
      } else {
        return false;
      }
    } else {
      durationSection = new WebmFloat('Duration', 'Float');
      durationSection.setValue(duration);
      infoSection.data.push({
        id: 0x489,
        data: durationSection
      });
    }

    // Default time scale to 1 millisecond (1,000,000 nanoseconds)
    timeScaleSection.setValue(1000000);
    infoSection.updateByData();
    segmentSection.updateByData();
    this.updateByData();

    return true;
  }
  toBlob(mimeType = 'video/webm') {
    return new Blob([this.source.buffer], { type: mimeType });
  }
}

/**
 * Injects duration metadata into a WebM Blob so that video player timelines become seekable.
 *
 * @param {Blob} blob - The raw WebM Blob from MediaRecorder
 * @param {number} durationMs - Duration of the recording in milliseconds
 * @returns {Promise<Blob>} The patched Blob with duration metadata
 */
export async function patchWebmDuration(blob, durationMs) {
  if (!blob || !(blob instanceof Blob)) return blob;
  if (!durationMs || durationMs <= 0) return blob;

  // Only patch WebM blobs
  if (blob.type && !blob.type.includes('webm')) return blob;

  try {
    const arrayBuffer = await blob.arrayBuffer();
    const file = new WebmFile(new Uint8Array(arrayBuffer));
    if (file.fixDuration(durationMs)) {
      return file.toBlob(blob.type);
    }
    return blob;
  } catch {
    // If parsing fails gracefully fallback to the original blob
    return blob;
  }
}

export default patchWebmDuration;
