export const categories = [
  { id: 'all', label_vn: 'Tất cả', label_en: 'All', label_ja: 'すべて', icon: 'Sparkles' },
  { id: 'pdf', label_vn: 'PDF & Tài liệu', label_en: 'PDF & Documents', label_ja: 'PDF・ドキュメント', icon: 'FileText' },
  { id: 'image', label_vn: 'Ảnh & WebP', label_en: 'Images & WebP', label_ja: '画像・WebP', icon: 'Image' },
  { id: 'office', label_vn: 'Kế toán & Hóa đơn', label_en: 'Finance & Invoices', label_ja: '会計・請求書', icon: 'FileSpreadsheet' },
  { id: 'utils', label_vn: 'Tiện ích', label_en: 'Utilities', label_ja: '便利ツール', icon: 'Wrench' },
  { id: 'ai', label_vn: 'Dịch thuật & AI', label_en: 'AI & Translation', label_ja: 'AI・翻訳', icon: 'Globe' },
  // Nhóm riêng cho miniapp tạm dừng. Chúng không xuất hiện ở bất kỳ nhóm nào
  // khác, kể cả "Tất cả công cụ", nhưng vẫn được liệt kê ở đây để nhắc rằng
  // các công cụ này đang chờ phát triển tiếp.
  { id: 'in-development', label_vn: 'Đang phát triển', label_en: 'In development', label_ja: '開発中', icon: 'Wrench' }
];

// Nhóm sản phẩm / Tên miền (Domain Groups) chuẩn hóa
export const TOOL_GROUPS = {
  common: {
    id: 'common',
    name: {
      vi: 'Công cụ',
      en: 'Tools',
      ja: 'ツール',
    },
  },
  'japan-life': {
    id: 'japan-life',
    country: 'JP',
    name: {
      vi: 'Cuộc sống tại Nhật',
      en: 'Japan Life',
      ja: '日本生活',
    },
  },
  'vietnam-life': {
    id: 'vietnam-life',
    country: 'VN',
    name: {
      vi: 'Cuộc sống tại Việt Nam',
      en: 'Vietnam Life',
      ja: 'ベトナム生活',
    },
  },
};

/** Lấy group của miniapp, mặc định an toàn về 'common' nếu chưa khai báo */
export const getToolGroup = (tool) => tool?.group || 'common';

// Miniapp tạm dừng phát triển. Chúng không được build vào portal, không mở được
// từ URL/command palette, và chỉ xuất hiện trong nhóm "Đang phát triển" — không
// nằm trong bất kỳ nhóm nào khác, kể cả "Tất cả công cụ". Xem
// hub/src/tools-in-development/README.md trước khi mở lại bất kỳ công cụ nào.
export const IN_DEVELOPMENT = 'in-development';

const toolGovernance = {
  'image-convert': {
    readiness: 'beta',
    processing: 'browser',
    priority: 3,
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'screen-capture': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'screen-recorder': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility'
  },
  'barcode-qr': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'pdf-toolkit': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'pdf-overlay': {
    readiness: IN_DEVELOPMENT,
    processing: 'browser',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển. Luồng hiện tại dựng HTML thay vì overlay lên PDF nguồn và còn rủi ro XSS; sẽ làm lại bằng pdf-lib khi có nhu cầu.'
  },
  'legal-studio': {
    readiness: IN_DEVELOPMENT,
    processing: 'backend-antigravity',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển. Phụ thuộc quyết định runtime Antigravity và kiểm thử đầu ra pháp lý.'
  },
  'long-translator': {
    readiness: IN_DEVELOPMENT,
    processing: 'backend-antigravity',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển theo định hướng sản phẩm; sẽ nghiên cứu lại khi cần.'
  },
  'certificate-studio': {
    readiness: IN_DEVELOPMENT,
    processing: 'manual',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển. Cần sanitize SVG/HTML đầu vào và bỏ dữ liệu mẫu gây hiểu nhầm.'
  },
  // priority chỉ đánh dấu ba miniapp ưu tiên sản phẩm (kế toán, hóa đơn, ảnh);
  // omniconvert là tiện ích nên không mang số ưu tiên.
  'omniconvert': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'excel-mapping': {
    readiness: 'experimental',
    processing: 'hybrid',
    outputPurpose: 'reference'
  },
  'editor-studio': { readiness: 'experimental', processing: 'browser', outputPurpose: 'reference' },
  'invoice-studio': {
    readiness: 'beta',
    processing: 'browser',
    priority: 2,
    outputPurpose: 'reference',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'contract-auditor': {
    readiness: IN_DEVELOPMENT,
    processing: 'browser',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển. Luồng hiện tại chưa đọc đủ ba bộ chứng từ và còn fallback dữ liệu giả.'
  },
  'auto-bi': { readiness: 'experimental', processing: 'browser', outputPurpose: 'reference' },
  'policy-assistant': {
    readiness: IN_DEVELOPMENT,
    processing: 'browser',
    outputPurpose: 'reference',
    unavailableReason: 'Tạm dừng phát triển. Cần kho chính sách có nguồn, phiên bản và ngày hiệu lực do pháp chế duyệt.'
  },
  'accounting-reconcile': {
    readiness: 'beta',
    processing: 'browser',
    priority: 1,
    outputPurpose: 'reference',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'tax-calculator': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'watermark-studio': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'id-photo-studio': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'business-card-studio': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-07'
  },
  'invoice-xml-fetcher': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility'
  },
  'flappy-bird': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility'
  },
  'toolio-ninja': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility'
  },
  'japan-tax-simulator': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'tax',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'social-insurance-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'social-insurance-eligibility-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'national-pension-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'dependent-insurance-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'overtime-calculator-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'paid-leave-checker-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'unemployment-eligibility-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'unemployment-benefit-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'leaving-job-wizard-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'guide',
    regulatory: true,
  },
  'maternity-allowance-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'childcare-leave-eligibility-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'childcare-benefit-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
  },
  'child-allowance-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  },
  'birth-wizard-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-10',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'guide',
    regulatory: true,
  },
  'moving-cost-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-11',
    group: 'japan-life',
    domain: 'housing',
    country: 'JP',
    type: 'simulator',
    regulatory: true,
  },
  'moving-admin-checker-jp': {
    readiness: 'beta',
    processing: 'browser',
    outputPurpose: 'utility',
    verified: true,
    verifiedAt: '2026-09-11',
    group: 'japan-life',
    domain: 'housing',
    country: 'JP',
    type: 'checker',
    regulatory: true,
  }
};


const toolDefinitions = [
  {
    id: 'business-card-studio',
    name_vn: 'Tạo Danh Thiếp',
    name_en: 'Business Card Maker',
    name_ja: '名刺作成',
    desc_vn: 'Thiết kế danh thiếp chuẩn in 300 DPI kèm bù xén 3mm & dấu Tonbo. Quét AI OCR từ ảnh danh thiếp cũ, 28 phong cách và in hàng loạt nhân viên.',
    desc_en: 'Commercial 300 DPI business card maker with 3mm bleed & Japanese Tonbo marks. AI OCR old cards, 28 templates & CSV batch employee generator.',
    desc_ja: '塗り足し3mm・トンボ付き300 DPI印刷用名刺ジェネレーター。名刺写真からのAI OCR認識、28種類のテンプレート、CSV社員一括作成対応。',
    category: 'image',
    icon: 'Contact',
    gradient: 'from-blue-600 via-indigo-600 to-amber-500',
    color: '#3b82f6',
    badge: 'PRINT READY',
    popular: true,
    tags: ['business card', 'namecard', 'danh thiếp', 'meishi', '名刺', 'in ấn', 'tonbo', 'トンボ', 'ocr', 'vcard', 'qr', 'print']
  },
  {
    id: 'id-photo-studio',
    name_vn: 'Tạo Ảnh Thẻ & Hộ Chiếu',
    name_en: 'ID & Passport Photo',
    name_ja: '証明写真・パスポート写真',
    desc_vn: 'Tách nền AI Studio HD, căn chuẩn khuôn mặt theo lưới ICAO/Combini, xuất file đơn Ultra HD và sheet in 300/600 DPI.',
    desc_en: 'AI Studio HD background removal, ICAO standard face framing, Ultra HD single photo & 300/600 DPI combini print sheet export.',
    desc_ja: 'AI高精度背景透過、規格準拠の自動顔位置調整、ウルトラHD単体出力およびコンビニ印刷用シート生成。',
    category: 'image',
    icon: 'UserCheck',
    gradient: 'from-blue-600 via-indigo-600 to-cyan-500',
    color: '#2563eb',
    badge: 'AI & PHOTO',
    popular: true,
    tags: ['id photo', 'passport', 'ảnh thẻ', 'hộ chiếu', 'combini', 'cv', 'visa', 'ai matting', '履歴書']
  },
  {
    id: 'image-convert',
    name_vn: 'Nén Ảnh Đa Năng',
    name_en: 'Multi-Purpose Image Compressor',
    name_ja: '画像圧縮・変換',
    desc_vn: 'Chuyển đổi hàng loạt PNG, JPG, GIF và WebP, nén dung lượng và so sánh chất lượng trực quan.',
    desc_en: 'Batch convert PNG, JPG, GIF and WebP images, compress and visually compare output.',
    desc_ja: 'PNG、JPG、GIF、WebPを一括変換し、圧縮して画質を比較します。',
    category: 'image',
    icon: 'Image',
    gradient: 'from-emerald-500 to-teal-600',
    color: '#10b981',
    badge: 'POPULAR',
    popular: true,
    tags: ['image', 'webp', 'convert', 'png', 'jpg', 'gif', 'compress', 'ảnh']
  },
  {
    id: 'screen-capture',
    name_vn: 'Chụp Màn Hình',
    name_en: 'Screen Capture',
    name_ja: '画面キャプチャ',
    desc_vn: 'Chụp nhanh màn hình, kéo chọn vùng tự động copy Clipboard 1-chạm và biên tập vẽ mũi tên, ghi chú, làm mờ.',
    desc_en: 'Fast screen capture, instant auto-copy to clipboard on snipping release, with live vector annotation & blur.',
    desc_ja: '画面を素早くキャプチャ、選択領域を即時クリップボードにコピーし、矢印や文字注釈・ぼかしを追加。',
    category: 'image',
    icon: 'Camera',
    gradient: 'from-brand-500 to-cyan-500',
    color: '#7c3aed',
    badge: 'CLIPBOARD',
    popular: true,
    tags: ['screenshot', 'capture', 'chụp màn hình', 'clipboard', 'snip', 'annotate', 'mũi tên', 'arrow', 'blur']
  },
  {
    id: 'screen-recorder',
    name_vn: 'Quay Màn Hình',
    name_en: 'Screen Recorder',
    name_ja: '画面録画',
    desc_vn: 'Ghi video màn hình, cửa sổ hoặc thẻ trình duyệt kèm âm thanh. Hoạt động 100% trên trình duyệt, không tốn RAM, tối ưu cho máy cấu hình thấp.',
    desc_en: 'Record screen, window or tab with audio. 100% client-side, zero RAM bloat, optimized for low-spec devices.',
    desc_ja: '画面・ウィンドウ・タブを音声付きで録画。100%ブラウザ完結、低スペック端末でも超軽量動作。',
    category: 'utils',
    icon: 'Video',
    gradient: 'from-rose-500 to-amber-500',
    color: '#ef4444',
    badge: 'LIGHTWEIGHT',
    tags: ['screen-recorder', 'record', 'video', 'quay màn hình', 'recording', 'low-spec', 'screen', 'audio']
  },
  {
    id: 'barcode-qr',
    name_vn: 'Tạo Mã QR & Barcode',
    name_en: 'QR & Barcode Generator',
    name_ja: 'QRコード・バーコード生成',
    desc_vn: 'Tạo mã QR nghệ thuật nhúng logo, gradient màu và mã vạch 1D chuẩn GS1 (Code128, EAN-13, UPC, ITF-14) 100% offline.',
    desc_en: 'Create styled QR codes with custom logos, dual gradients, and GS1 industrial 1D barcodes 100% in-browser.',
    desc_ja: 'ロゴ埋め込みQRコード、グラデーションカラー、GS1産業用バーコード（Code128、EAN-13、UPC）を完全ローカルで生成。',
    category: 'utils',
    icon: 'QrCode',
    gradient: 'from-brand-600 via-indigo-600 to-cyan-500',
    color: '#8b5cf6',
    badge: 'GS1 & LOGO',
    popular: true,
    tags: ['qr', 'barcode', 'mã vạch', 'mã qr', 'ean', 'code128', 'upc', 'itf-14', 'logo', 'batch', 'generator']
  },
  {
    id: 'pdf-toolkit',
    name_vn: 'Công Cụ PDF Đa Năng',
    name_en: 'PDF Multi-Tool',
    name_ja: '万能PDFツール',
    desc_vn: 'Tách, gộp và nén file PDF 100% trên trình duyệt — tất cả trong một.',
    desc_en: 'Split, merge and compress PDF files 100% in-browser — all in one.',
    desc_ja: 'ブラウザ上で100%完結するPDF分割・結合・圧縮ツール。',
    category: 'pdf',
    icon: 'FileText',
    gradient: 'from-rose-500 via-violet-500 to-teal-500',
    color: '#8b5cf6',
    badge: '3-IN-1',
    popular: true,
    tags: ['pdf', 'split', 'tách', 'trích xuất', 'extract', 'merge', 'gộp', 'ghép', 'combine', 'compress', 'nén', 'thu nhỏ', 'dung lượng', 'size', 'slim', 'optimizer']
  },
  {
    id: 'pdf-overlay',
    name_vn: 'Đè Dữ Liệu Lên Form PDF',
    name_en: 'PDF Template Overlay',
    name_ja: 'PDF テンプレート重ね合わせ',
    desc_vn: 'Điền dữ liệu, văn bản, chữ ký trực tiếp lên phôi biểu mẫu PDF có sẵn.',
    desc_en: 'Overlay dynamic text, signatures, and fields onto pre-existing PDF forms.',
    desc_ja: '既存のPDFフォーム上にテキスト、署名、フィールドを重ねて入力します。',
    category: 'pdf',
    icon: 'Printer',
    gradient: 'from-fuchsia-500 to-purple-600',
    color: '#d946ef',
    badge: 'CANVAS',
    popular: false,
    tags: ['pdf', 'overlay', 'template', 'form', 'đè dữ liệu', 'chữ ký']
  },
  {
    id: 'legal-studio',
    name_vn: 'Soạn Thảo & Dịch Pháp Lý',
    name_en: 'Legal Document Studio',
    name_ja: '法律文書スタジオ',
    desc_vn: 'Soạn thảo, đối chiếu và dịch văn bản pháp lý 2 cột song ngữ chuẩn xác.',
    desc_en: 'Draft, compare, and translate legal contracts with dual-column bilingual alignment.',
    desc_ja: '2列のバイリンガル表示で契約書や法律文書を作成・翻訳します。',
    category: 'ai',
    icon: 'Scale',
    gradient: 'from-emerald-600 to-cyan-600',
    color: '#059669',
    badge: 'AI READY',
    popular: true,
    tags: ['legal', 'pháp lý', 'hợp đồng', 'song ngữ', 'dịch', 'contract']
  },
  {
    id: 'long-translator',
    name_vn: 'Dịch Tài Liệu Dài EJV',
    name_en: 'Long Doc & EJV Translator',
    name_ja: '長文ドキュメント翻訳',
    desc_vn: 'Dịch thuật tài liệu dài đa trang (Anh - Nhật - Việt) giữ nguyên bố cục định dạng.',
    desc_en: 'Translate multi-page documents (English, Japanese, Vietnamese) preserving formatting.',
    desc_ja: '書式を維持したまま長文ドキュメント（英語・日本語・ベトナム語）を翻訳します。',
    category: 'ai',
    icon: 'Globe',
    gradient: 'from-teal-500 to-cyan-600',
    color: '#0d9488',
    badge: 'EJV ENGINE',
    popular: true,
    tags: ['translator', 'dịch thuật', 'tiếng nhật', 'tiếng anh', 'long doc']
  },
  {
    id: 'certificate-studio',
    name_vn: 'Dịch Bằng Cấp & Chứng Chỉ',
    name_en: 'Certificate Studio',
    name_ja: '証明書・資格証スタジオ',
    desc_vn: 'Phân tích cấu trúc, dịch thuật và xuất bản mẫu bằng lái, bằng đại học, chứng chỉ A4.',
    desc_en: 'Analyze, translate and generate A4 print-ready certificates, diplomas, and licenses.',
    desc_ja: '卒業証明書、資格証、免許証のA4印刷レイアウトを作成・翻訳します。',
    category: 'ai',
    icon: 'Award',
    gradient: 'from-indigo-500 to-blue-600',
    color: '#6366f1',
    badge: 'A4 LAYOUT',
    popular: false,
    tags: ['certificate', 'bằng cấp', 'chứng chỉ', 'bằng lái', 'diploma']
  },
  {
    id: 'omniconvert',
    name_vn: 'Chuyển Đổi Đa Năng',
    name_en: 'Universal File Converter',
    name_ja: '万能ファイル変換',
    desc_vn: 'Chuyển đổi linh hoạt giữa DOCX, PPTX, XLSX, PDF, Markdown (.md), ảnh và TXT 100% bảo mật trên trình duyệt.',
    desc_en: 'Lightning-fast client-side conversion between DOCX, PPTX, XLSX, PDF, Markdown (.md), images, and TXT with zero server uploads.',
    desc_ja: 'サーバーにアップロードせずに、ブラウザ上でDOCX、PPTX、XLSX、PDF、Markdown (.md)、画像、TXTを相互に高速変換します。',
    category: 'pdf',
    icon: 'ArrowLeftRight',
    gradient: 'from-orange-500 to-amber-600',
    color: '#f97316',
    badge: 'NEW',
    popular: true,
    tags: ['convert', 'pdf', 'docx', 'pptx', 'xlsx', 'markdown', 'md', 'chuyển đổi']
  },
  {
    id: 'excel-mapping',
    name_vn: 'Tự Động Hóa & Mapping Excel',
    name_en: 'Excel Data Mapping',
    name_ja: 'Excel データマッピング',
    desc_vn: 'Tự động ánh xạ các cột dữ liệu Excel của khách hàng vào biểu mẫu nhà cung cấp.',
    desc_en: 'Automatically map customer Excel fields into supplier order templates.',
    desc_ja: '顧客のExcelデータをサプライヤーの発注書フォーマットに自動マッピングします。',
    category: 'utils',
    icon: 'FileSpreadsheet',
    gradient: 'from-blue-500 to-indigo-600',
    color: '#3b82f6',
    badge: 'AUTOMATION',
    popular: true,
    tags: ['excel', 'mapping', 'xlsx', 'data', 'tự động hóa']
  },
  {
    id: 'editor-studio',
    name_vn: 'Bộ Soạn Thảo Template Nâng Cao',
    name_en: 'Interactive Document Studio',
    name_ja: 'インタラクティブ文書エディタ',
    desc_vn: 'Trình tạo biểu mẫu tương tác, thiết kế dàn trang A4 và xuất file DOCX/PDF.',
    desc_en: 'Interactive form and template builder with smart layout formatting and DOCX/PDF export.',
    desc_ja: 'スマートなレイアウト書式設定とDOCX/PDF出力を備えた文書作成ツール。',
    category: 'pdf',
    icon: 'LayoutTemplate',
    gradient: 'from-indigo-600 to-purple-600',
    color: '#4f46e5',
    badge: 'DOCX EXPORT',
    popular: false,
    tags: ['editor', 'template', 'docx', 'form', 'soạn thảo']
  },
  {
    id: 'invoice-studio',
    name_vn: 'Tạo Đề Nghị Thanh Toán',
    name_en: 'Payment Request Maker',
    name_ja: '支払依頼書作成',
    desc_vn: 'Trích xuất dữ liệu hóa đơn điện tử XML/PDF và tự động xuất bảng Excel Đề nghị thanh toán.',
    desc_en: 'Extract electronic invoice XML/PDF data and generate Excel Payment Requests.',
    desc_ja: '電子請求書XML/PDFからデータを抽出し、支払依頼Excelを自動生成します。',
    category: 'office',
    icon: 'Receipt',
    gradient: 'from-amber-500 to-orange-600',
    color: '#f59e0b',
    badge: 'INVOICE AI',
    popular: true,
    tags: ['invoice', 'hóa đơn', 'thanh toán', 'xml', 'pdf', 'excel']
  },
  {
    id: 'invoice-xml-fetcher',
    name_vn: 'Lấy Hóa Đơn XML',
    name_en: 'Invoice XML Fetcher',
    name_ja: '請求書XML取得',
    desc_vn: 'Đọc mã tra cứu và link từ PDF hóa đơn, tải XML trực tiếp hoặc hỗ trợ 1 chạm mở cổng tra cứu.',
    desc_en: 'Extract lookup code and URL from PDF invoice, download XML directly or 1-click open provider portal.',
    desc_ja: '請求書PDFから検索コードとURLを抽出し、XMLを直接ダウンロードまたは照会ポータルをワンクリック起動。',
    category: 'office',
    icon: 'FileDown',
    gradient: 'from-blue-600 to-indigo-600',
    color: '#2563eb',
    badge: 'XML GET',
    popular: true,
    tags: ['invoice', 'hóa đơn', 'xml', 'tra cứu', 'pdf', 'minvoice', 'hilo', 'vnpt', 'viettel', 'misa']
  },
  {
    id: 'contract-auditor',
    name_vn: 'Đối Soát Hợp Đồng & Thanh Quyết Toán',
    name_en: 'Contract & Payment Auditor',
    name_ja: '契約書・支払突合監査',
    desc_vn: 'Đối chiếu chéo 3 chiều (Hợp đồng ↔ Biên bản nghiệm thu ↔ Hóa đơn) và phát hiện sai lệch.',
    desc_en: '3-way matching cross-audit between Contracts, Acceptance Records, and Invoices.',
    desc_ja: '契約書、検収書、請求書の3者間突合を行い、差異や上限超過を検出します。',
    category: 'office',
    icon: 'Scale',
    gradient: 'from-emerald-500 to-teal-600',
    color: '#10b981',
    badge: '3-WAY AUDIT',
    popular: true,
    tags: ['contract', 'hợp đồng', 'đối soát', 'nghiệm thu', 'audit', 'matching']
  },
  {
    id: 'auto-bi',
    name_vn: 'Phân Tích Dữ Liệu & Báo Cáo BI',
    name_en: 'Auto-BI Smart Analytics',
    name_ja: '自動BIデータ分析',
    desc_vn: 'Nạp file Excel/CSV thô, tự động nhận diện chỉ số, vẽ biểu đồ tương tác và sinh nhận xét điều hành.',
    desc_en: 'Upload raw Excel/CSV, auto-detect metrics, render interactive charts and executive insights.',
    desc_ja: 'Excel/CSVデータを読み込み、指標を自動集計してグラフと要約レポートを生成します。',
    category: 'office',
    icon: 'BarChart3',
    gradient: 'from-cyan-500 to-blue-600',
    color: '#06b6d4',
    badge: 'SMART BI',
    popular: true,
    tags: ['bi', 'chart', 'analytics', 'báo cáo', 'phân tích', 'excel', 'csv']
  },
  {
    id: 'policy-assistant',
    name_vn: 'Trợ Lý Quy Chế & Soạn Biểu Mẫu',
    name_en: 'Policy & Expense Assistant',
    name_ja: '規程・旅費申請アシスタント',
    desc_vn: 'Tra cứu định mức công tác phí theo vùng, tự động tính toán dự toán và xuất biểu mẫu đề xuất.',
    desc_en: 'Look up per-diem policy rates by region, auto-calculate travel budget and generate forms.',
    desc_ja: '地域別の旅費日当基準を参照し、出張予算を自動計算して申請書を作成します。',
    category: 'ai',
    icon: 'HelpCircle',
    gradient: 'from-purple-500 to-indigo-600',
    color: '#a855f7',
    badge: 'POLICY AI',
    popular: true,
    tags: ['policy', 'quy chế', 'công tác phí', 'expense', 'dự toán'],
  },
  {
    id: 'accounting-reconcile',
    name_vn: 'Đối Chiếu Kế Toán',
    name_en: 'Accounting Reconciliation',
    name_ja: '経理照合ツール',
    desc_vn: 'Tự động đối chiếu chênh lệch doanh thu và thuế GTGT giữa sổ kế toán nội bộ (511, 33311) và bảng kê thuế (BR).',
    desc_en: 'Automatically reconcile revenue and VAT discrepancies between internal ledgers (511, 33311) and tax invoices (BR).',
    desc_ja: '内部元帳（511、33311）と税金請求書（BR）の間の収益とVATの差異を自動的に照合します。',
    category: 'office',
    icon: 'Calculator',
    gradient: 'from-blue-600 to-indigo-700',
    color: '#4f46e5',
    badge: 'NEW',
    popular: true,
    tags: ['accounting', 'reconcile', 'đối chiếu', 'kế toán', 'thuế', 'doanh thu', '511', '33311', 'br', 'excel']
  },
  {
    id: 'tax-calculator',
    name_vn: 'Tính Thuế TNCN',
    name_en: 'Personal Income Tax Calculator',
    name_ja: '個人所得税計算（ベトナム）',
    desc_vn: 'Tính thuế TNCN lũy tiến 5 bậc 2026, chuyển đổi Gross ↔ Net, mức giảm trừ mới, bảo hiểm 4 vùng, tính thuế Freelancer, BĐS và BHXH rút 1 lần.',
    desc_en: 'Vietnam 2026 5-bracket PIT calculator, Gross ↔ Net conversion, region I-IV insurance ceilings, Freelancer, Real Estate & Lump-sum Social Insurance.',
    desc_ja: 'ベトナム2026年新5段階累進税率、Gross・Net相互換算、地域別保険上限、フリーランス・不動産譲渡・社会保険一括受給の計算ツール。',
    category: 'office',
    icon: 'Calculator',
    gradient: 'from-blue-600 via-indigo-600 to-teal-500',
    color: '#2563eb',
    badge: '2026 READY',
    popular: true,
    tags: ['thuế tncn', 'tax', 'pit', 'gross net', 'lương', 'salary', 'bhxh', 'bhtn', 'quuyết toán', 'freelancer', 'bất động sản', 'office']
  },
  {
    id: 'japan-tax-simulator',
    name_vn: 'Mô Phỏng Thuế Nhật Bản',
    name_en: 'Japan Tax Guide & Simulator',
    name_ja: '日本の税金ガイド・シミュレーター',
    desc_vn: 'Mô phỏng toàn diện các loại thuế & bảo hiểm xã hội Nhật Bản (Thuế TNCN, Thuế cư trú, Kinh doanh, Tiêu thụ, Pháp nhân). Chẩn đoán tự động điều kiện kê khai 確定申告 & mô phỏng What-If. 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Comprehensive Japan tax & social insurance simulator (Income, Resident, Enterprise, Consumption & Corporate taxes). Auto-diagnose Kakutei Shinkoku necessity with interactive What-If simulation. 100% client-side.',
    desc_ja: '働き方に合わせた税金・社会保険料の自動判定と概算シミュレーション（所得税・住民税・個人事業税・消費税・法人税）。確定申告の要否診断とWhat-If比較に対応。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'tax',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'Coins',
    gradient: 'from-rose-500 via-red-600 to-amber-500',
    color: '#e11d48',
    badge: 'JAPAN TAX',
    popular: true,
    tags: ['japan tax', 'thuế nhật', '日本の税金', '確定申告', '所得税', '住民税', '個人事業税', '消費税', '法人税', '社会保険', 'gensen', 'nenkin', 'hoken', 'shinkoku', 'office']
  },
  {
    id: 'social-insurance-jp',
    name_vn: 'Mô Phỏng BHXH Nhật Bản',
    name_en: 'Japan Social Insurance Simulator',
    name_ja: '社会保険料シミュレーター',
    desc_vn: 'Mô phỏng chính xác BHYT Kyokai Kenpo (47 tỉnh thành), Quỹ hỗ trợ nuôi con 2026, Chăm sóc người già, Hưu trí Kosei Nenkin & Thất nghiệp theo bảng chuẩn thù lao tháng. 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Accurate simulation of Kyokai Kenpo health insurance (47 prefectures), Child Support Fund 2026, Care Insurance, Welfare Pension & Employment Insurance via Standard Monthly Remuneration. 100% client-side.',
    desc_ja: '協会けんぽ（47都道府県）・子ども子育て支援金（2026年）・介護保険・厚生年金・雇用保険の標準報酬月額に基づく精密試算。従業員控除と会社負担の2つの視点に対応。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'ShieldCheck',
    gradient: 'from-blue-600 via-cyan-600 to-emerald-500',
    color: '#0284c7',
    badge: '令和8年度',
    popular: true,
    tags: ['社会保険', '健康保険', '厚生年金', '雇用保険', '介護保険', '子ども子育て支援金', '標準報酬月額', 'insurance', 'pension', 'bảo hiểm', 'lương hưu', 'kenpo', 'shakai hoken', 'japan life', 'office']
  },
  {
    id: 'social-insurance-eligibility-jp',
    name_vn: 'Kiểm Tra Điều Kiện Tham Gia BHXH',
    name_en: 'Social Insurance Eligibility Checker',
    name_ja: '社会保険加入判定',
    desc_vn: 'Chẩn đoán điều kiện bắt buộc tham gia BHXH (BHYT & Hưu trí Kosei Nenkin) cho lao động Part-time, Baito theo quy chuẩn mở rộng 2026 (20h/tuần, 8.8 vạn, DN 51 người). 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Diagnose whether part-time or contract workers must enroll in Social Insurance under the 2026 expanded criteria (20h/wk, 88k JPY/mo, 51+ employees). 100% client-side.',
    desc_ja: 'パート・アルバイト・短時間労働者が社会保険（健康保険・厚生年金）の義務的加入対象かを判定。週20時間・月額8.8万円・51人以上企業の新基準に対応。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'UserCheck',
    gradient: 'from-emerald-500 via-teal-600 to-cyan-500',
    color: '#059669',
    badge: '判定チェッカー',
    popular: true,
    tags: ['社会保険加入判定', '社会保険', '106万円の壁', '短時間労働者', 'パート', 'アルバイト', '厚生年金', '健康保険', 'eligibility', 'insurance', 'bảo hiểm', 'lương hưu', 'shakai hoken', 'japan life', 'office']
  },
  {
    id: 'national-pension-jp',
    name_vn: 'Tra Cứu & Tính Phí Hưu Trí Quốc Dân',
    name_en: 'Japan National Pension Guide & Simulator',
    name_ja: '国民年金ガイド＆保険料シミュレーター',
    desc_vn: 'Tra cứu biểu phí Hưu trí Quốc dân FY2026 (17,920円/tháng), mức chiết khấu nộp trước (前納), tỷ lệ hưởng lương hưu theo các mức miễn giảm (免除・猶予) và quy tắc truy đóng (追納). 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Simulate Japan National Pension FY2026 premiums (17,920 JPY/mo), advance payment discounts, old-age pension reflection under exemptions/deferments, and retroactive backpayments. 100% client-side.',
    desc_ja: '令和8年度（月額17,920円）の国民年金保険料、前納割引額、全額・一部免除や学生納付特例における将来の年金額反映率、10年以内の追納ルールを精密試算・解説。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'PiggyBank',
    gradient: 'from-amber-500 via-orange-500 to-rose-500',
    color: '#f59e0b',
    badge: '国民年金',
    popular: true,
    tags: ['国民年金', '年金', '保険料', '前納', '免除', '納付猶予', '学生納付特例', '追納', '付加年金', 'pension', 'insurance', 'hưu trí', 'lương hưu', 'bảo hiểm', 'japan life', 'office']
  },
  {
    id: 'dependent-insurance-jp',
    name_vn: 'Kiểm Tra Người Phụ Thuộc BHXH',
    name_en: 'Social Insurance Dependent Checker',
    name_ja: '社会保険の扶養判定',
    desc_vn: 'Chẩn đoán điều kiện làm người phụ thuộc BHYT (0円 phí bảo hiểm) theo quan hệ thân nhân 3 đời, sống chung/riêng, trần thu nhập tương lai 130 vạn/180 vạn và tỷ lệ chu cấp. Phân biệt độc lập với thuế. 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Evaluate health insurance dependent status (0 JPY premium contribution) via 3rd-degree kinship, cohabitation, 1.3M/1.8M JPY income ceilings, and remittance support. Strictly separated from tax. 100% client-side.',
    desc_ja: '健康保険の被扶養者（保険料負担なし）の認定要件を判定。3親等内の親族範囲・同居別居の別・将来見込み年収（130万/180万円）および主たる生計維持関係を網羅。税法上の扶養とは厳格に分離。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'insurance',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'HeartHandshake',
    gradient: 'from-rose-500 via-pink-600 to-amber-500',
    color: '#e11d48',
    badge: '扶養判定',
    popular: true,
    tags: ['社会保険の扶養判定', '社会保険', '被扶養者', '130万円の壁', '180万円の壁', '健康保険', '国民年金第3号', '扶養', 'dependent', 'insurance', 'pension', 'bảo hiểm', 'lương hưu', 'japan life', 'office']
  },
  {
    id: 'overtime-calculator-jp',
    name_vn: 'Tính Tiền Làm Thêm Giờ (残業代)',
    name_en: 'Japan Overtime Pay Calculator',
    name_ja: '残業代シミュレーター',
    desc_vn: 'Mô phỏng chính xác tiền lương phụ trội làm thêm giờ (ngoài giờ 25%, vượt 60h/tháng 50%, làm đêm 25%, ngày nghỉ 35%). Chuẩn Điều 37 Luật Tiêu chuẩn Lao động Nhật Bản. 100% xử lý nội bộ trình duyệt.',
    desc_en: 'Accurate simulation of Japanese statutory overtime pay (standard 25%, over 60h/mo 50%, late-night 25%, holiday 35%). Compliant with Art. 37 Labor Standards Act. 100% client-side.',
    desc_ja: '労働基準法第37条に準拠した時間外・休日・深夜労働の割増賃金（月60時間超の50%割増対応）を精密試算。除外賃金控除や月平均所定労働時間換算に対応。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'Clock',
    gradient: 'from-blue-600 via-indigo-600 to-cyan-500',
    color: '#3b82f6',
    badge: '労働基準法',
    popular: true,
    tags: ['残業代シミュレーター', '残業代', '割増賃金', '時間外労働', '休日労働', '深夜労働', '60時間超', 'overtime', 'tăng ca', 'làm thêm giờ', 'tiền tăng ca', 'zangyou', 'japan life', 'office']
  },
  {
    id: 'paid-leave-checker-jp',
    name_vn: 'Kiểm Tra Phép Năm (有給休暇)',
    name_en: 'Japan Paid Leave Entitlement Checker',
    name_ja: '有給休暇チェッカー',
    desc_vn: 'Tra cứu ngày nghỉ phép có lương theo thâm niên, lịch cấp phép tỷ lệ cho part-time/baito, điều kiện chuyên cần 80% và nghĩa vụ nghỉ 5 ngày/năm. Chuẩn Điều 39 Luật Tiêu chuẩn Lao động.',
    desc_en: 'Check statutory annual paid leave entitlements by tenure, proportional part-time grants, 80% attendance rule, and mandatory 5-day leave compliance tracker under Art. 39 Labor Standards Act.',
    desc_ja: '労働基準法第39条に基づく法定有給休暇日数、パート・アルバイトの比例付与、出勤率8割要件、年5日取得義務の進捗を正確に算定・可視化。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'CalendarCheck',
    gradient: 'from-emerald-600 via-teal-600 to-cyan-600',
    color: '#059669',
    badge: '労働基準法',
    popular: true,
    tags: ['有給休暇チェッカー', '有給休暇', '年次有給休暇', '有給', '年5日取得義務', '比例付与', '出勤率8割', 'paid leave', 'annual leave', 'phép năm', 'nghỉ phép', 'yukyu', 'japan life', 'office']
  },
  {
    id: 'unemployment-eligibility-jp',
    name_vn: 'Điều Kiện Trợ Cấp Thất Nghiệp (失業給付)',
    name_en: 'Japan Unemployment Eligibility Checker',
    name_ja: '失業給付受給資格チェッカー',
    desc_vn: 'Kiểm tra điều kiện hưởng trợ cấp thất nghiệp, phân loại diện thôi việc (công ty sa thải 6 tháng vs tự ý nghỉ 12 tháng), thời gian hạn chế chi trả (0 vs 2 tháng), và thủ tục gia hạn tối đa 4 năm.',
    desc_en: 'Check statutory employment insurance eligibility, separation classification (company dismissal 6 mos vs voluntary 12 mos), benefit restriction periods (none vs 2 mos), and up to 4-year extension.',
    desc_ja: '雇用保険法に基づく離職理由別の受給資格判定（会社都合6ヶ月 vs 自己都合12ヶ月）、給付制限期間（なし vs 2ヶ月）、受給期間延長（最大4年）を判定。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'FileSearch',
    gradient: 'from-blue-700 via-indigo-700 to-teal-600',
    color: '#1d4ed8',
    badge: '雇用保険法',
    popular: true,
    tags: ['失業給付受給資格チェッカー', '失業給付', '受給資格', '基本手当', '雇用保険', '特定受給資格者', '特定理由離職者', '給付制限', '受給期間延長', '離職票', 'unemployment', 'thất nghiệp', 'trợ cấp thất nghiệp', 'hello work', 'japan life', 'office']
  },
  {
    id: 'unemployment-benefit-jp',
    name_vn: 'Mô Phỏng Trợ Cấp Thất Nghiệp (失業給付)',
    name_en: 'Japan Unemployment Benefit Simulator',
    name_ja: '失業給付シミュレーター',
    desc_vn: 'Tính toán chính xác mức trợ cấp cơ bản hàng ngày (基本手当日額), số ngày hưởng (90〜330 ngày), tổng số tiền nhận và tỷ lệ trượt 50%〜80% theo luật MHLW. 100% xử lý trên trình duyệt.',
    desc_en: 'Statutory calculation of Basic Daily Allowance, prescribed benefit days (90 to 330 days), total payouts, and 50% to 80% sliding scale rates under MHLW regulations. 100% client-side.',
    desc_ja: '雇用保険法に基づく基本手当日額、所定給付日数（90日〜330日）、受給総額、50%〜80%スライド給付率を正確に試算。100%ブラウザ完結。',
    category: 'office',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'Coins',
    gradient: 'from-blue-600 via-indigo-600 to-emerald-600',
    color: '#2563eb',
    badge: '雇用保険法',
    popular: true,
    tags: ['失業給付シミュレーター', '失業手当', '失業保険', '基本手当日額', '賃金日額', '所定給付日数', '受給総額', '給付率', 'unemployment', 'trợ cấp thất nghiệp', 'tiền thất nghiệp', 'thất nghiệp', 'japan life', 'office']
  },
  {
    id: 'leaving-job-wizard-jp',
    name_vn: 'Hướng Dẫn Nghỉ Việc Tại Nhật',
    name_en: 'Japan Resignation Guide & Wizard',
    name_ja: '退職手続きガイド＆オーケストレーター',
    desc_vn: 'Điều phối toàn diện thủ tục khi thôi việc: thời hạn báo trước 14 ngày, 3 lựa chọn BHYT, chuyển đổi lương hưu quốc dân, khấu trừ thuế cư trú và hồ sơ Hello Work.',
    desc_en: 'Comprehensive Japan resignation roadmap: 14-day notice, 3 health insurance options, national pension switch, resident tax collection, and Hello Work procedures.',
    desc_ja: '民法・労働法・社会保険に基づく退職手続き総合ガイド。申出2週間前ルール、健康保険の3択（任意継続・国保・扶養）、年金種別変更、住民税一括徴収、ハローワーク受給。',
    category: 'office',
    group: 'japan-life',
    domain: 'employment',
    country: 'JP',
    type: 'guide',
    regulatory: true,
    icon: 'Compass',
    gradient: 'from-sky-500 via-indigo-600 to-emerald-600',
    color: '#0284c7',
    badge: '退職・法的手続き',
    popular: true,
    tags: ['退職手続き', '退職', '退職届', '離職票', '任意継続', '国民健康保険', '国民年金', '住民税', '一括徴収', 'ハローワーク', 'resignation', 'leaving job', 'nghỉ việc', 'thôi việc', 'thủ tục thôi việc', 'japan life', 'office']
  },
  {
    id: 'maternity-allowance-jp',
    name_vn: 'Tính Trợ Cấp Thai Sản',
    name_en: 'Maternity Allowance Simulator',
    name_ja: '出産手当金シミュレーター',
    desc_vn: 'Mô phỏng trợ cấp thai sản BHYT Nhật Bản (2/3 lương chuẩn): tính chính xác số ngày được hưởng, mức trợ cấp ngày và tổng số tiền.',
    desc_en: 'Simulate Japan health insurance maternity allowance (2/3 standard remuneration): exact eligible days, daily rate, and total amount.',
    desc_ja: '健康保険法第102条に基づく産前産後休業中の給料補償（標準報酬月額の3分の2）：支給日数・日額・総支給額を正確に試算。',
    category: 'office',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'Baby',
    gradient: 'from-pink-500 to-rose-600',
    color: '#ec4899',
    badge: '健康保険法',
    popular: true,
    tags: ['出産手当金', '産前産後休業', '健康保険', '協会けんぽ', 'thai sản', 'maternity allowance', 'nghỉ sinh', 'trợ cấp thai sản', 'lương nghỉ thai sản', 'bảo hiểm thai sản', 'japan life', 'family']
  },
  {
    id: 'childcare-leave-eligibility-jp',
    name_vn: 'Kiểm Tra Nghỉ Chăm Con & Trợ Cấp',
    name_en: 'Childcare Leave & Benefit Checker',
    name_ja: '育児休業・給付チェッカー',
    desc_vn: 'Chẩn đoán quyền nghỉ chăm con theo luật lao động & điều kiện nhận 4 chế độ trợ cấp BHTN (tiêu chuẩn, sau sinh cho bố, thưởng 13%, rút ngắn giờ).',
    desc_en: 'Diagnose statutory childcare leave rights and eligibility for 4 Employment Insurance benefit schemes (standard, Papa Ikukyu, post-birth bonus, short-time work).',
    desc_ja: '育児・介護休業法に基づく休業権利と、雇用保険の4大給付（育休給付・産後パパ育休・休業支援加算・時短就業給付）の受給要件を判定。',
    category: 'office',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'Users',
    gradient: 'from-indigo-600 via-purple-600 to-pink-500',
    color: '#6366f1',
    badge: '育介法・雇用保険',
    popular: true,
    tags: ['育児休業', '育児休業給付金', '産後パパ育休', '出生後休業支援給付金', '育児時短就業給付金', '雇用保険', '育休', 'childcare leave', 'nghỉ chăm con', 'trợ cấp chăm con', 'japan life', 'family']
  },
  {
    id: 'childcare-benefit-jp',
    name_vn: 'Tính Trợ Cấp Nghỉ Chăm Con',
    name_en: 'Childcare Leave Benefit Simulator',
    name_ja: '育児休業給付シミュレーター',
    desc_vn: 'Mô phỏng tiền trợ cấp nghỉ chăm con (giai đoạn 67% và 50%), tiền hỗ trợ sau sinh 13%, trợ cấp rút ngắn giờ làm 10% và miễn giảm bảo hiểm xã hội.',
    desc_en: 'Simulate childcare leave benefits (67% & 50% tiers), post-birth 13% bonus, short-time work 10% benefit, and social insurance tax exemptions.',
    desc_ja: '育児休業給付金（67%・50%）、出生後休業支援（+13%）、育児時短就業給付（10%）および社会保険料免除・非課税実質手取り額をシミュレーション。',
    category: 'office',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'calculator',
    regulatory: true,
    icon: 'Coins',
    gradient: 'from-amber-500 via-orange-500 to-rose-500',
    color: '#f59e0b',
    badge: '雇用保険法',
    popular: true,
    tags: ['育児休業給付金', '育児休業', '育休手当', '出生後休業支援給付金', '育児時短就業給付金', '社会保険料免除', '非課税', '雇用保険', 'childcare benefit', 'trợ cấp nghỉ chăm con', 'bảo hiểm thất nghiệp', 'japan life', 'family']
  },
  {
    id: 'child-allowance-jp',
    name_vn: 'Kiểm Tra Trợ Cấp Trẻ Em',
    name_en: 'Child Allowance Checker',
    name_ja: '児童手当チェッカー',
    desc_vn: 'Chẩn đoán số tiền trợ cấp trẻ em theo cải cách 10/2024: Bỏ trần thu nhập, mở rộng đến 18 tuổi (hết cấp 3), con thứ 3 nhận 30.000円/tháng, đếm thứ tự con đến 22 tuổi.',
    desc_en: 'Diagnose child allowance benefits under the Oct 2024 reform: No income caps, extended to age 18 (high school), 30,000 JPY/mo for 3rd child, and bimonthly payout.',
    desc_ja: 'こども家庭庁の2024年10月抜本拡充（所得制限撤廃・高校生年代18歳まで延長・第3子月3万円・22歳年度末カウント・偶数月年6回支給）に対応。',
    category: 'office',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'Baby',
    gradient: 'from-pink-500 via-rose-500 to-amber-500',
    color: '#ec4899',
    badge: '児童手当法',
    popular: true,
    tags: ['児童手当', 'こども家庭庁', '所得制限撤廃', '多子加算', '第3子', '高校生年代', 'child allowance', 'trợ cấp trẻ em', 'trợ cấp nuôi con', 'japan life', 'family']
  },
  {
    id: 'birth-wizard-jp',
    name_vn: 'Cẩm Nang Mang Thai & Nuôi Con',
    name_en: 'Birth & Childcare Guide',
    name_ja: '妊娠・出産・育児ガイド',
    desc_vn: 'Bản đồ lộ trình 6 giai đoạn từ lúc mang thai đến con 2 tuổi: Tính khoản hỗ trợ sinh con 500.000円, hạn nộp hồ sơ, cơ quan phụ trách và chính sách riêng theo địa phương.',
    desc_en: 'Complete 6-stage lifecycle roadmap from pregnancy to age 2: 500,000 JPY childbirth grant settlement, filing deadlines, municipal desks, and local policy integration.',
    desc_ja: '妊娠判明から出産・育休・職場復帰（2歳到達）まで全6ステージの手続きロードマップ。出産育児一時金50万円の直接支払精算や自治体独自制度に対応。',
    category: 'office',
    group: 'japan-life',
    domain: 'family',
    country: 'JP',
    type: 'guide',
    regulatory: true,
    icon: 'Compass',
    gradient: 'from-rose-500 via-purple-600 to-indigo-600',
    color: '#e11d48',
    badge: 'ライフイベント',
    popular: true,
    tags: ['妊娠', '出産', '育児', '出産育児一時金', '母子手帳', '保活', '出生届', 'birth wizard', 'mang thai', 'sinh con', 'nuôi con', 'japan life', 'family']
  },
  {
    id: 'moving-cost-jp',
    name_vn: 'Mô Phỏng Chi Phí Chuyển Nhà',
    name_en: 'Moving Cost Simulator',
    name_ja: '引越し費用シミュレーター',
    desc_vn: 'Ước tính cước phí chuyển nhà theo quy mô hộ gia đình, cự ly và mùa cao điểm. Tra cứu biểu phí phạt hủy hợp đồng theo quy ước chuẩn của Bộ Giao thông MLIT.',
    desc_en: 'Moving cost simulator by household size, distance, and peak seasonality. Reference MLIT standard cancellation fee guidelines.',
    desc_ja: '世帯人数・移動距離・時期・時間帯別の引越し概算相場シミュレーター。国土交通省「標準引越運送約款」に基づく解約手数料を明示。',
    category: 'office',
    group: 'japan-life',
    domain: 'housing',
    country: 'JP',
    type: 'simulator',
    regulatory: true,
    icon: 'Truck',
    gradient: 'from-amber-500 via-orange-600 to-rose-600',
    color: '#f59e0b',
    badge: '住まい',
    popular: true,
    tags: ['引越し', '引越し費用', '相場', 'トラック', '標準引越運送約款', 'moving cost', 'chuyển nhà', 'cước phí', 'japan life', 'housing']
  },
  {
    id: 'moving-admin-checker-jp',
    name_vn: 'Thủ Tục Hành Chính Chuyển Nhà',
    name_en: 'Moving Administrative Checker',
    name_ja: '引越し行政手続きナビ',
    desc_vn: 'Kiểm tra hạn chót luật định 14 ngày cho 転出届 (chuyển đi), 転入届 (chuyển đến), 転居届 (đổi địa chỉ). Hướng dẫn dịch vụ Một Cửa chuyển nhà online trên MyNaPortal.',
    desc_en: 'Check statutory 14-day deadlines for moving-out (Tenshutsu) and moving-in (Tennyu). Guidance for MyNaPortal Online Moving One-Stop Service.',
    desc_ja: '住民基本台帳法に基づく転出届・転入届・転居届の法定14日期限とマイナポータル「引越しワンストップサービス」の判定ナビ。',
    category: 'office',
    group: 'japan-life',
    domain: 'housing',
    country: 'JP',
    type: 'checker',
    regulatory: true,
    icon: 'Building2',
    gradient: 'from-blue-600 via-indigo-600 to-sky-600',
    color: '#2563eb',
    badge: '行政ナビ',
    popular: true,
    tags: ['引越し', '転出届', '転入届', '転居届', 'マイナポータル', 'ワンストップ', '住民基本台帳法', 'moving procedure', 'thủ tục chuyển nhà', 'chuyển khẩu', 'japan life', 'housing']
  },
  {
    id: 'watermark-studio',

    name_vn: 'Đóng Dấu Tài Liệu',
    name_en: 'Document Watermark',
    name_ja: '文書透かし・押印',
    desc_vn: 'Đóng dấu watermark văn bản hoặc logo lên PDF, DOCX, XLSX, PPTX và ảnh. Tùy chỉnh màu sắc, độ đậm nhạt, bố cục lưới/đơn. 100% xử lý trên trình duyệt.',
    desc_en: 'Stamp text or logo watermarks on PDF, DOCX, XLSX, PPTX and images. Customizable color, opacity, tiled/single layout. 100% client-side processing.',
    desc_ja: 'PDF、DOCX、XLSX、PPTXや画像にテキストまたはロゴの透かしを追加。色、透明度、レイアウトをカスタマイズ。100%ブラウザ処理。',
    category: 'utils',
    icon: 'Stamp',
    gradient: 'from-indigo-500 to-violet-600',
    color: '#6366f1',
    badge: 'NEW',
    popular: true,
    tags: ['watermark', 'stamp', 'đóng dấu', 'bản quyền', 'confidential', 'draft', 'logo', 'pdf', 'docx', 'xlsx', 'pptx', 'ảnh']
  },
  {
    id: 'flappy-bird',
    name_vn: 'Flappy Bird',
    name_en: 'Flappy Bird',
    name_ja: 'フラッピーバード',
    desc_vn: 'Minigame giải trí thư giãn, điều khiển chú chim bay qua các đường ống.',
    desc_en: 'Relaxing arcade minigame, guide the bird through the obstacle pipes.',
    desc_ja: 'リラックスできるアーケードミニゲーム。障害物の土管を通り抜けよう。',
    category: 'utils',
    icon: 'Gamepad2',
    gradient: 'from-amber-400 to-orange-500',
    color: '#f59e0b',
    badge: 'GAME',
    popular: false,
    tags: ['flappy bird', 'game', 'minigame', 'chim bay', 'arcade', 'giải trí', 'relax', 'utils']
  },
  {
    id: 'toolio-ninja',
    name_vn: 'Toolio Ninja Run',
    name_en: 'Toolio Ninja Run',
    name_ja: 'ツーリオ・ニンジャ ラン',
    desc_vn: 'Endless runner vui nhộn: cùng Ninja vượt dặm trường Nhật - Việt, né tránh và chém tan các vấn đề văn phòng!',
    desc_en: 'Fun endless runner: run across Japan & Vietnam, slash and solve real office file problems!',
    desc_ja: '爽快エンドレスランナー：日本とベトナムを駆け抜け、オフィスの課題を一刀両断！',
    category: 'utils',
    icon: 'Swords',
    gradient: 'from-blue-600 via-cyan-500 to-amber-500',
    color: '#0284c7',
    badge: 'NEW GAME',
    popular: true,
    tags: ['game', 'minigame', 'ninja', 'runner', 'endless runner', 'arcade', 'giải trí', 'relax', 'chém', 'jump', 'slash', 'pdf', 'toolio']
  }
];

export const tools = toolDefinitions.map((tool) => {
  const merged = {
    readiness: 'experimental',
    processing: 'browser',
    outputPurpose: 'reference',
    verified: false,
    group: 'common',
    domain: null,
    country: null,
    type: 'utility',
    regulatory: false,
    ...tool,
    ...toolGovernance[tool.id],
  };
  // Bảo đảm tương thích ngược tuyệt đối: nếu chưa có group thì mặc định an toàn là 'common'
  if (!merged.group) {
    merged.group = 'common';
  }
  return merged;
});

export const isInDevelopment = (tool) => tool?.readiness === IN_DEVELOPMENT;

/** Miniapp đã được xác nhận ổn định (verified) và được bảo vệ khỏi thay đổi không chủ đích. */
export const isVerified = (tool) => Boolean(tool?.verified);

/** Danh sách các miniapp đã đạt chuẩn verified. */
export const verifiedTools = tools.filter(isVerified);

/** Miniapp được build vào portal và mở được từ UI/URL. */
export const activeTools = tools.filter((tool) => !isInDevelopment(tool));

/** Miniapp đã tạm dừng; giữ lại trong registry để portal công bố trạng thái. */
export const inDevelopmentTools = tools.filter(isInDevelopment);
