/**
 * @file offices/index.js
 * Danh bạ chính thức các Cơ quan đại diện ngoại giao và lãnh sự Việt Nam tại Nhật Bản.
 * Dữ liệu đã được kiểm chứng từ trang thông tin chính thức của ĐSQ và TLSQ.
 */

export const CONSULAR_OFFICES = {
  tokyo: {
    id: 'tokyo',
    name_vn: 'Đại sứ quán Việt Nam tại Tokyo',
    name_en: 'Embassy of the Socialist Republic of Vietnam in Japan (Tokyo)',
    name_ja: '在日ベトナム社会主義共和国大使館（東京）',
    type: 'embassy',
    flag: '🇻🇳',
    address: {
      postal_code: '151-0062',
      prefecture: 'Tokyo',
      line: '50-11 Motoyoyogi-cho, Shibuya-ku, Tokyo',
      line_ja: '東京都渋谷区元代々木町50-11',
      map_url: 'https://goo.gl/maps/K7gAeYreUb5QCRQq6',
    },
    contact: {
      switchboard: ['+81-3-3466-3311', '+81-3-3466-3313', '+81-3-3466-3314'],
      fax: ['+81-3-3466-7652', '+81-3-3466-3312'],
      consular_email: 'vnconsular@vnembassy.jp',
      general_email: 'vietnamembassy-japan@vnembassy.jp',
      citizen_protection_email: 'baohocongdan@vnembassy.jp',
      citizen_protection_hotline: '+81-80-3590-9136',
      labor_hotline: '+81-80-7142-6688',
      education_hotline: '+81-80-7506-1987',
      mofa_citizen_protection: '+84-98-184-8484',
    },
    working_hours: {
      reception_morning: '09:00 - 12:00 (Thứ 2 - Thứ 6)',
      return_afternoon: '14:00 - 17:00 (Thứ 2 - Thứ 6)',
      closed: 'Thứ 7, Chủ Nhật và các ngày nghỉ lễ theo quy định của Việt Nam và Nhật Bản',
    },
    official_website: 'https://vnembassy-jp.org',
    notes: 'Tiếp nhận hồ sơ trực tiếp hoặc qua bưu điện tùy loại thủ tục. Với thủ tục hộ tịch (khai sinh, kết hôn), đương sự phải có mặt trực tiếp ký sổ bộ.',
    last_verified: '2026-09-12',
  },
  osaka: {
    id: 'osaka',
    name_vn: 'Tổng Lãnh sự quán Việt Nam tại Osaka',
    name_en: 'Consulate General of Vietnam in Osaka',
    name_ja: '在大阪ベトナム社会主義共和国総領事館',
    type: 'consulate_general',
    flag: '🇻🇳',
    address: {
      postal_code: '590-0952',
      prefecture: 'Osaka',
      line: '4-2-15 Ichinocho Higashi, Sakai-ku, Sakai-shi, Osaka',
      line_ja: '大阪府堺市堺区市之町東4-2-15',
      map_url: 'https://goo.gl/maps/Q3iZ7s6zR8wF6y4x7',
    },
    contact: {
      switchboard: ['+81-72-221-6666'],
      fax: ['+81-72-221-6667'],
      consular_phones: [
        '+81-72-221-6603',
        '+81-72-224-6887',
        '+81-72-221-6607',
        '+81-72-221-6608',
      ],
      consular_email: 'vnconsulate-info@vnconsulate-osaka.org',
      general_email: 'vnconsulate-info@vnconsulate-osaka.org',
      citizen_protection_email: 'baohocongdan.osaka@gmail.com',
      citizen_protection_hotline: '+81-90-4769-6789',
      mofa_citizen_protection: '+84-98-184-8484',
    },
    working_hours: {
      reception_morning: '09:00 - 12:00 (Thứ 2 - Thứ 6)',
      return_afternoon: '15:30 - 17:00 (Thứ 2 - Thứ 6)',
      closed: 'Thứ 7, Chủ Nhật và các ngày nghỉ lễ theo quy định',
    },
    official_website: 'https://vnconsulate-osaka.org',
    notes: 'Phụ trách khu vực Kansai, Shikoku và Chugoku. Hỗ trợ nộp hồ sơ qua đường bưu điện đối với các thủ tục được phép (kèm bì thư khứ hồi LetterPack).',
    last_verified: '2026-09-12',
  },
  fukuoka: {
    id: 'fukuoka',
    name_vn: 'Tổng Lãnh sự quán Việt Nam tại Fukuoka',
    name_en: 'Consulate General of Vietnam in Fukuoka',
    name_ja: '在福岡ベトナム社会主義共和国総領事館',
    type: 'consulate_general',
    flag: '🇻🇳',
    address: {
      postal_code: '810-0801',
      prefecture: 'Fukuoka',
      line: '4F, Aqua Hakata, 5-3-8 Nakasu, Hakata-ku, Fukuoka-shi, Fukuoka',
      line_ja: '福岡県福岡市博多区中洲5-3-8 アクア博多4階',
      map_url: 'https://goo.gl/maps/bY4nZt3Wf1cM7d7A9',
    },
    contact: {
      switchboard: ['+81-92-263-7668'],
      fax: ['+81-92-263-7676'],
      consular_email: 'tlsq.fukuoka@gmail.com',
      general_email: 'vnconsulate.fukuoka@gmail.com',
      citizen_protection_hotline: '+81-80-4279-7302',
      mofa_citizen_protection: '+84-98-184-8484',
    },
    working_hours: {
      reception_morning: '09:00 - 12:00 (Thứ 2 - Thứ 6)',
      return_afternoon: '14:00 - 17:00 (Thứ 2 - Thứ 6)',
      closed: 'Thứ 7, Chủ Nhật và các ngày nghỉ lễ',
    },
    official_website: 'https://vnconsulate-fukuoka.org',
    notes: 'Phụ trách chính thức khu vực 8 tỉnh thành Kyushu và Okinawa. Tiếp nhận hồ sơ trực tiếp và qua bưu điện cho các thủ tục được quy định.',
    last_verified: '2026-09-12',
  },
  honorary_nagoya: {
    id: 'honorary_nagoya',
    name_vn: 'Văn phòng Lãnh sự danh dự tại Nagoya',
    name_en: 'Honorary Consulate of Vietnam in Nagoya',
    name_ja: '在名古屋ベトナム名誉領事館',
    type: 'honorary_consulate',
    flag: '🇻🇳',
    address: {
      postal_code: '460-0003',
      prefecture: 'Aichi',
      line: 'Nagoya-shi, Aichi',
      line_ja: '愛知県名古屋市',
    },
    status: 'local_support_only',
    notes: 'Cơ quan Lãnh sự danh dự chủ yếu hỗ trợ kết nối hữu nghị, thương mại và hỗ trợ cộng đồng tại địa phương. Về thẩm quyền xử lý thủ tục hành chính lãnh sự (hộ chiếu, khai sinh, kết hôn, hợp pháp hóa), người cư trú tại Aichi nộp hồ sơ tại Đại sứ quán Việt Nam tại Tokyo.',
    last_verified: '2026-09-12',
  },
  honorary_kushiro: {
    id: 'honorary_kushiro',
    name_vn: 'Văn phòng Lãnh sự danh dự tại Kushiro (Hokkaido)',
    name_en: 'Honorary Consulate of Vietnam in Kushiro',
    name_ja: '在釧路ベトナム名誉領事館',
    type: 'honorary_consulate',
    flag: '🇻🇳',
    address: {
      postal_code: '085-0015',
      prefecture: 'Hokkaido',
      line: 'Kushiro-shi, Hokkaido',
      line_ja: '北海道釧路市',
    },
    status: 'local_support_only',
    notes: 'Hỗ trợ tại địa phương cho khu vực Hokkaido. Thẩm quyền thụ lý thủ tục hành chính lãnh sự chính thức thuộc về Đại sứ quán Việt Nam tại Tokyo.',
    last_verified: '2026-09-12',
  },
};

export const getOfficeById = (id) => CONSULAR_OFFICES[id] || CONSULAR_OFFICES.tokyo;
