/**
 * Biểu mẫu Tờ khai đề nghị cấp hộ chiếu phổ thông ở nước ngoài (Mẫu TK02)
 * Ban hành kèm theo Thông tư số 31/2023/TT-BCA ngày 20/07/2023 của Bộ Công an.
 * 
 * Lưu ý: Tờ khai sử dụng cho công dân Việt Nam đang cư trú tại nước ngoài (Nhật Bản)
 * đề nghị cấp mới, cấp lại hộ chiếu phổ thông khi hết hạn, bị mất, hỏng hoặc tách hộ chiếu.
 */

export const passportTK02Form = {
  id: 'form_passport_tk02',
  code: 'TK02',
  title: {
    vi: 'Tờ khai đề nghị cấp hộ chiếu phổ thông (Mẫu TK02)',
    en: 'Passport Application Form (Form TK02)',
    ja: '一般旅券発給申請書（様式TK02）',
  },
  standardBasis: 'Thông tư số 31/2023/TT-BCA ngày 20/07/2023 của Bộ Công an',
  sha256Fingerprint: '4f2d71b8e84a259c719e7a89bc60de649f1a2386ac80f12d83b4e94f923b3781',
  status: 'VERIFIED',
  sourceUrl: 'https://vnembassy-jp.org/vi/cap-ho-chieu-lan-dau-cho-nguoi-chua-tung-duoc-cap-ho-chieu-viet-nam',
  applicableOffices: ['tokyo_embassy', 'osaka_consulate', 'fukuoka_consulate'],
  printOrientation: 'portrait',
  paperSize: 'A4',

  // Cấu trúc các trường dữ liệu
  fields: [
    {
      id: 'applicantName',
      label: 'Họ và tên (chữ in hoa)',
      type: 'text',
      placeholder: 'NGUYỄN VĂN A',
      required: true,
      transform: (val) => val?.toUpperCase() || '',
      validationRegex: '^([A-ZÀ-Ỵ\\s]+)$',
      validationMessage: 'Vui lòng nhập họ tên in hoa không dấu hoặc có dấu tiếng Việt',
    },
    {
      id: 'gender',
      label: 'Giới tính',
      type: 'select',
      options: [
        { value: 'Nam', label: 'Nam' },
        { value: 'Nữ', label: 'Nữ' },
      ],
      required: true,
    },
    {
      id: 'dob',
      label: 'Ngày, tháng, năm sinh',
      type: 'date',
      required: true,
    },
    {
      id: 'birthPlace',
      label: 'Nơi sinh (tỉnh, thành phố hoặc quốc gia)',
      type: 'text',
      placeholder: 'Hà Nội, Việt Nam hoặc Tokyo, Nhật Bản',
      required: true,
    },
    {
      id: 'idCardNumber',
      label: 'Số CCCD / CMND / Mã định danh cá nhân',
      type: 'text',
      placeholder: '12 chữ số CCCD hoặc 9 số CMND',
      required: false,
    },
    {
      id: 'idCardIssueDate',
      label: 'Ngày cấp CCCD / CMND',
      type: 'date',
      required: false,
    },
    {
      id: 'idCardIssuePlace',
      label: 'Nơi cấp CCCD / CMND',
      type: 'text',
      placeholder: 'Cục Cảnh sát QLHC về TTXH',
      required: false,
    },
    {
      id: 'ethnic',
      label: 'Dân tộc',
      type: 'text',
      defaultValue: 'Kinh',
      required: true,
    },
    {
      id: 'religion',
      label: 'Tôn giáo',
      type: 'text',
      defaultValue: 'Không',
      required: true,
    },
    {
      id: 'permanentAddressVN',
      label: 'Địa chỉ thường trú hoặc tạm trú trước khi xuất cảnh tại Việt Nam',
      type: 'text',
      placeholder: 'Số nhà, đường, phường/xã, quận/huyện, tỉnh/thành phố',
      required: false,
    },
    {
      id: 'residenceAddressJP',
      label: 'Địa chỉ cư trú tại Nhật Bản (Kèm Romaji hoặc Kanji)',
      type: 'textarea',
      placeholder: '〒160-0022 Tokyo-to, Shinjuku-ku, Shinjuku 1-2-3...',
      required: true,
    },
    {
      id: 'phoneNumber',
      label: 'Số điện thoại liên hệ tại Nhật Bản',
      type: 'tel',
      placeholder: '080-1234-5678',
      required: true,
    },
    {
      id: 'email',
      label: 'Địa chỉ Email nhận thông báo',
      type: 'email',
      placeholder: 'example@gmail.com',
      required: true,
    },
    {
      id: 'occupation',
      label: 'Nghề nghiệp / Nơi làm việc tại Nhật Bản',
      type: 'text',
      placeholder: 'Kỹ sư CNTT / Công ty ABC KK',
      required: false,
    },
    {
      id: 'fatherName',
      label: 'Họ và tên cha',
      type: 'text',
      placeholder: 'NGUYỄN VĂN B (Năm sinh: 1965)',
      required: false,
    },
    {
      id: 'motherName',
      label: 'Họ và tên mẹ',
      type: 'text',
      placeholder: 'TRẦN THỊ C (Năm sinh: 1968)',
      required: false,
    },
    {
      id: 'spouseName',
      label: 'Họ và tên vợ/chồng (nếu có)',
      type: 'text',
      placeholder: 'LÊ THỊ D (Năm sinh: 1995)',
      required: false,
    },
    {
      id: 'oldPassportNumber',
      label: 'Hộ chiếu phổ thông cấp lần gần nhất (Số hộ chiếu)',
      type: 'text',
      placeholder: 'B1234567 hoặc C1234567 (Bỏ trống nếu cấp lần đầu)',
      required: false,
    },
    {
      id: 'oldPassportIssueDate',
      label: 'Ngày cấp hộ chiếu cũ',
      type: 'date',
      required: false,
    },
    {
      id: 'oldPassportIssuePlace',
      label: 'Cơ quan cấp hộ chiếu cũ',
      type: 'text',
      placeholder: 'Cục Quản lý xuất nhập cảnh hoặc ĐSQ VN tại Nhật Bản',
      required: false,
    },
    {
      id: 'requestType',
      label: 'Nội dung đề nghị cấp hộ chiếu',
      type: 'select',
      options: [
        { value: 'cap_lai_sap_het_han', label: 'Cấp lại do hộ chiếu sắp hết hạn / đã hết hạn' },
        { value: 'cap_lai_do_mat', label: 'Cấp lại do bị mất hộ chiếu' },
        { value: 'cap_lai_do_hong', label: 'Cấp lại do hộ chiếu bị hỏng / rách / ướt' },
        { value: 'cap_lan_dau', label: 'Cấp hộ chiếu lần đầu' },
        { value: 'cap_thay_doi_thong_tin', label: 'Cấp lại do thay đổi thông tin nhân thân (họ tên, CCCD)' },
      ],
      required: true,
      defaultValue: 'cap_lai_sap_het_han',
    },
    {
      id: 'passportChipOption',
      label: 'Loại hộ chiếu đề nghị cấp',
      type: 'select',
      options: [
        { value: 'co_gan_chip', label: 'Cấp hộ chiếu có gắn chíp điện tử' },
        { value: 'khong_gan_chip', label: 'Cấp hộ chiếu không gắn chíp điện tử' },
      ],
      required: true,
      defaultValue: 'co_gan_chip',
    },
  ],

  // Dữ liệu mẫu khởi tạo
  initialValues: {
    applicantName: '',
    gender: 'Nam',
    dob: '',
    birthPlace: '',
    idCardNumber: '',
    idCardIssueDate: '',
    idCardIssuePlace: '',
    ethnic: 'Kinh',
    religion: 'Không',
    permanentAddressVN: '',
    residenceAddressJP: '',
    phoneNumber: '',
    email: '',
    occupation: '',
    fatherName: '',
    motherName: '',
    spouseName: '',
    oldPassportNumber: '',
    oldPassportIssueDate: '',
    oldPassportIssuePlace: '',
    requestType: 'cap_lai_sap_het_han',
    passportChipOption: 'co_gan_chip',
  },
};
