/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "../packages/core/src/**/*.{js,ts,jsx,tsx}",
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'surface-canvas': 'rgb(var(--surface-canvas-rgb) / <alpha-value>)',
        'surface': 'rgb(var(--surface-rgb) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim-rgb) / <alpha-value>)',
        'surface-bright': 'rgb(var(--surface-bright-rgb, var(--surface-container-high-rgb)) / <alpha-value>)',
        'surface-subtle': 'rgb(var(--surface-subtle-rgb) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low-rgb) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container-rgb) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest-rgb) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant-rgb) / <alpha-value>)',
        'border-subtle': 'rgb(var(--border-subtle-rgb) / <alpha-value>)',
        'outline': 'rgb(var(--outline-rgb) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant-rgb) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant-rgb) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface-rgb, var(--on-surface-rgb)) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface-rgb, var(--surface-canvas-rgb)) / <alpha-value>)',
        'primary': 'rgb(var(--primary-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary-rgb) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container-rgb) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container-rgb) / <alpha-value>)',
        'brand-cyan-bright': 'rgb(var(--brand-cyan-bright-rgb) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary-rgb) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary-rgb) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container-rgb) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container-rgb) / <alpha-value>)',
        'brand-emerald-deep': 'rgb(var(--brand-emerald-deep-rgb) / <alpha-value>)',
        'tertiary': 'rgb(var(--tertiary-rgb) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--on-tertiary-rgb) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container-rgb) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container-rgb) / <alpha-value>)',
        'error': 'rgb(var(--error-rgb) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error-rgb, 255 255 255) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container-rgb) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container-rgb, var(--on-surface-rgb)) / <alpha-value>)',
        // Preserve legacy brand for backwards compatibility
        brand: {
          50: '#f0fdf4',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
        }
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-12': '48px',
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
        'sidebar-width': '280px'
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'title-sm': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'label-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
      },
      maxWidth: {
        'content': '1240px',
      }
    },
  },
  plugins: [],
}
